from scale_factors_config import *
from ttalps_extra_collections import extraEventCollections
from ttalps_signal_selections import *

nEvents = -1
printEveryNevents = 10000

runDefaultHistograms = True
runTriggerHistograms = False
runPileupHistograms = False
runLLPNanoAODHistograms = True
runMuonMatchingHistograms = True
runGenMuonHistograms = True

weightsBranchName = "genWeight"
eventsTreeNames = ("Events",)

pileupScaleFactorsPath = "/nfs/dust/cms/user/jniedzie/ttalps_cms/pileup_scale_factors.root"
pileupScaleFactorsHistName = "pileup_scale_factors"

applyScaleFactors = {
  "muon": True,
  "muonTrigger": True,
  "pileup": True,
  "bTagging": True,
}

defaultHistParams = (
#  collection             variable               bins    xmin    xmax    dir
  ("Event"              , "PV_npvs"             , 300   , 0     , 300   , ""  ),
  ("Event"              , "PV_npvsGood"         , 300   , 0     , 300   , ""  ),
  ("Event"              , "MET_pt"              , 1000  , 0     , 1000  , ""  ),
  
  ("Event"              , "nMuon"               , 50    , 0     , 50    , ""  ),
  ("Muon"               , "pt"                  , 2000  , 0     , 1000  , ""  ),
  ("Muon"               , "eta"                 , 300   , -3    , 3     , ""  ),
  ("Muon"               , "dxy"                 , 8000  , -1000  , 1000   , ""  ),
  ("Muon"               , "dz"                  , 8000  , -1000  , 1000   , ""  ),
  
  ("Event"              , "nTightMuons"         , 50    , 0     , 50    , ""  ),
  ("TightMuons"         , "pt"                  , 2000  , 0     , 1000  , ""  ),
  ("TightMuons"         , "eta"                 , 300   , -3    , 3     , ""  ),
  ("TightMuons"         , "dxy"                 , 8000  , -1000  , 1000   , ""  ),
  ("TightMuons"         , "dz"                  , 8000  , -1000  , 1000   , ""  ),
  ("TightMuons"         , "pfRelIso04_all"      , 2000  , -10   , 10    , ""  ),
  ("TightMuons"         , "pfRelIso03_chg"      , 2000  , -10   , 10    , ""  ),
  ("TightMuons"         , "pfRelIso03_all"      , 2000  , -10   , 10    , ""  ),
  ("TightMuons"         , "tkRelIso"            , 2000  , -10   , 10    , ""  ),
  ("TightMuons"         , "miniPFRelIso_chg"    , 2000  , -10   , 10    , ""  ),
  ("TightMuons"         , "miniPFRelIso_all"    , 2000  , -10   , 10    , ""  ),
  ("TightMuons"         , "jetRelIso"           , 2000  , -10   , 10    , ""  ),

  
  ("Event"              , "nLooseMuons"         , 50    , 0     , 50    , ""  ),
  ("LooseMuons"         , "pt"                  , 2000  , 0     , 1000  , ""  ),
  ("LooseMuons"         , "eta"                 , 300   , -3    , 3     , ""  ),
  ("LooseMuons"         , "phi"                 , 300   , -3    , 3     , ""  ),
  ("LooseMuons"         , "dxy"                 , 8000  , -1000  , 1000   , ""  ),
  ("LooseMuons"         , "dz"                  , 8000  , -1000  , 1000   , ""  ),
  ("LooseMuons"         , "pfRelIso04_all"      , 2000  , -10   , 10    , ""  ),
  ("LooseMuons"         , "pfRelIso03_chg"      , 2000  , -10   , 10    , ""  ),
  ("LooseMuons"         , "pfRelIso03_all"      , 2000  , -10   , 10    , ""  ),
  ("LooseMuons"         , "tkRelIso"            , 2000  , -10   , 10    , ""  ),
  ("LooseMuons"         , "miniPFRelIso_chg"    , 2000  , -10   , 10    , ""  ),
  ("LooseMuons"         , "miniPFRelIso_all"    , 2000  , -10   , 10    , ""  ),
  ("LooseMuons"         , "jetRelIso"           , 2000  , -10   , 10    , ""  ),
  
  ("Event"              , "nElectron"           , 50    , 0     , 50    , ""  ),
  ("Electron"           , "pt"                  , 2000  , 0     , 1000  , ""  ),
  ("Electron"           , "eta"                 , 300   , -3    , 3     , ""  ),
  ("Electron"           , "dxy"                 , 8000  , -1000  , 1000   , ""  ),
  ("Electron"           , "dz"                  , 8000  , -1000  , 1000   , ""  ),
  
  ("Event"              , "nLooseElectrons"     , 50    , 0     , 50    , ""  ),
  ("LooseElectrons"     , "pt"                  , 2000  , 0     , 1000  , ""  ),
  ("LooseElectrons"     , "eta"                 , 300   , -3    , 3     , ""  ),
  ("LooseElectrons"     , "dxy"                 , 8000  , -1000  , 1000   , ""  ),
  ("LooseElectrons"     , "dz"                  , 8000  , -1000  , 1000   , ""  ),
  
  ("Event"              , "nJet"                , 50    , 0     , 50    , ""  ),
  ("Jet"                , "pt"                  , 2000  , 0     , 1000  , ""  ),
  ("Jet"                , "eta"                 , 300   , -3    , 3     , ""  ),
  ("Jet"                , "phi"                 , 300   , -3    , 3     , ""  ),
  ("Jet"                , "btagDeepB"           , 200   , -1    , 1     , ""  ),
  
  ("Event"              , "nGoodJets"           , 50    , 0     , 50    , ""  ),
  ("GoodJets"           , "pt"                  , 2000  , 0     , 2000  , ""  ),
  ("GoodJets"           , "eta"                 , 300   , -3    , 3     , ""  ),
  ("GoodJets"           , "phi"                 , 300   , -3    , 3     , ""  ),
  ("GoodJets"           , "btagDeepB"           , 200   , -1    , 1     , ""  ),
  ("GoodJets"           , "btagDeepFlavB"       , 200   , -1    , 1     , ""  ),
  
  ("Event"                    , "nGoodMediumBtaggedJets"    , 50    , 0     , 50    , ""  ),
  ("GoodMediumBtaggedJets"    , "pt"                  , 2000  , 0     , 2000  , ""  ),
  ("GoodMediumBtaggedJets"    , "eta"                 , 300   , -3    , 3     , ""  ),
  ("GoodMediumBtaggedJets"    , "phi"                 , 300   , -3    , 3     , ""  ),
  ("GoodMediumBtaggedJets"    , "btagDeepB"           , 200   , -1    , 1     , ""  ),
  ("GoodMediumBtaggedJets"    , "btagDeepFlavB"       , 200   , -1    , 1     , ""  ),
  
  ("Event"                    , "nGoodNonTightBtaggedJets" , 50    , 0     , 50    , ""  ),
  ("GoodNonTightBtaggedJets"  , "pt"                  , 2000  , 0     , 2000  , ""  ),
  ("GoodNonTightBtaggedJets"  , "eta"                 , 300   , -3    , 3     , ""  ),
  ("GoodNonTightBtaggedJets"  , "phi"                 , 300   , -3    , 3     , ""  ),
  ("GoodNonTightBtaggedJets"  , "btagDeepB"           , 200   , -1    , 1     , ""  ),
  ("GoodNonTightBtaggedJets"  , "btagDeepFlavB"       , 200   , -1    , 1     , ""  ),

)

LLPNanoAOD_defaultHistParams = (

  ("Muon"               , "idx"                 , 50    , 0     , 50    , ""  ),
  ("Muon"               , "dsaMatch1"           , 100   , 0     , 100   , ""  ),
  ("Muon"               , "dsaMatch1idx"        , 100   , 0     , 100   , ""  ),
  ("Muon"               , "dsaMatch2"           , 100   , 0     , 100   , ""  ),
  ("Muon"               , "dsaMatch2idx"        , 100   , 0     , 100   , ""  ),
  ("Muon"               , "dsaMatch3"           , 100   , 0     , 100   , ""  ),
  ("Muon"               , "dsaMatch3idx"        , 100   , 0     , 100   , ""  ),
  ("Muon"               , "dsaMatch4"           , 100   , 0     , 100   , ""  ),
  ("Muon"               , "dsaMatch4idx"        , 100   , 0     , 100   , ""  ),
  ("Muon"               , "dsaMatch5"           , 100   , 0     , 100   , ""  ),
  ("Muon"               , "dsaMatch5idx"        , 100   , 0     , 100   , ""  ),
  ("Muon"               , "outerEta"            , 300   , -3    , 3     , ""  ),
  ("Muon"               , "outerPhi"            , 300   , -3    , 3     , ""  ),

  ("LooseMuons"               , "idx"                 , 50    , 0     , 50    , ""  ),
  ("LooseMuons"               , "dzPV"                , 8000  , -1000 , 1000  , ""  ),
  ("LooseMuons"               , "dxyPVTraj"           , 8000  , -1000 , 1000  , ""  ),
  ("LooseMuons"               , "dxyPVSigned"         , 8000  , -1000 , 1000  , ""  ),
  ("LooseMuons"               , "ip3DPVSigned"        , 8000  , -1000 , 1000  , ""  ),
  # ("LooseMuons"               , "dxyBS"               , 8000  , -1000 , 1000  , ""  ),
  ("LooseMuons"               , "dzBS"                , 8000  , -1000 , 1000  , ""  ),
  ("LooseMuons"               , "dxyBSTraj"           , 8000  , -1000 , 1000  , ""  ),
  ("LooseMuons"               , "dxyBSSigned"         , 8000  , -1000 , 1000  , ""  ),
  ("LooseMuons"               , "ip3DBSSigned"        , 8000  , -1000 , 1000  , ""  ),
  ("LooseMuons"               , "dsaMatch1"           , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "dsaMatch1idx"        , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "dsaMatch2"           , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "dsaMatch2idx"        , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "dsaMatch3"           , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "dsaMatch3idx"        , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "dsaMatch4"           , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "dsaMatch4idx"        , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "dsaMatch5"           , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "dsaMatch5idx"        , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "outerEta"            , 300   , -3    , 3     , ""  ),
  ("LooseMuons"               , "outerPhi"            , 300   , -3    , 3     , ""  ),
  ("LooseMuons"               , "trkNumPlanes"        , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "trkNumHits"          , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "trkNumDTHits"        , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "trkNumCSCHits"       , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "trkNumPixelHits"     , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "trkNumTrkLayers"     , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "normChi2"            , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "trkPt"               , 2000  , 0     , 1000  , ""  ),
  ("LooseMuons"               , "trkPtErr"            , 2000  , 0     , 1000  , ""  ),

  ("Event"              , "nDSAMuon"            , 50    , 0     , 50    , ""  ),
  ("DSAMuon"            , "idx"                 , 50    , 0     , 50    , ""  ),
  ("DSAMuon"            , "pt"                  , 2000  , 0     , 1000  , ""  ),
  ("DSAMuon"            , "eta"                 , 300   , -3    , 3     , ""  ),
  ("DSAMuon"            , "dxy"                 , 8000  , -1000 , 1000  , ""  ),
  ("DSAMuon"            , "dz"                  , 8000  , -1000 , 1000  , ""  ),
  ("DSAMuon"            , "muonMatch1"          , 100   , 0     , 100   , ""  ),
  ("DSAMuon"            , "muonMatch1idx"       , 100   , 0     , 100   , ""  ),
  ("DSAMuon"            , "muonMatch2"          , 100   , 0     , 100   , ""  ),
  ("DSAMuon"            , "muonMatch2idx"       , 100   , 0     , 100   , ""  ),
  ("DSAMuon"            , "muonMatch3"          , 100   , 0     , 100   , ""  ),
  ("DSAMuon"            , "muonMatch3idx"       , 100   , 0     , 100   , ""  ),
  ("DSAMuon"            , "muonMatch4"          , 100   , 0     , 100   , ""  ),
  ("DSAMuon"            , "muonMatch4idx"       , 100   , 0     , 100   , ""  ),
  ("DSAMuon"            , "muonMatch5"          , 100   , 0     , 100   , ""  ),
  ("DSAMuon"            , "muonMatch5idx"       , 100   , 0     , 100   , ""  ),
  ("DSAMuon"            , "outerEta"            , 300   , -3    , 3     , ""  ),
  ("DSAMuon"            , "outerPhi"            , 300   , -3    , 3     , ""  ),
  ("DSAMuon"            , "displacedID"         , 50    , 0     , 50    , ""  ),

  ("Event"              , "nLooseDSAMuons"            , 50    , 0     , 50    , ""  ),
  ("LooseDSAMuons"            , "idx"                 , 50    , 0     , 50    , ""  ),
  ("LooseDSAMuons"            , "pt"                  , 2000  , 0     , 1000  , ""  ),
  ("LooseDSAMuons"            , "eta"                 , 300   , -3    , 3     , ""  ),
  ("LooseDSAMuons"            , "phi"                 , 300   , -3    , 3     , ""  ),
  ("LooseDSAMuons"            , "dxy"                 , 20000  , -2000    , 2000  , ""  ),
  ("LooseDSAMuons"            , "dz"                  , 20000  , -2000    , 2000  , ""  ),
  ("LooseDSAMuons"            , "idx"                 , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "dzPV"                , 20000  , -2000    , 2000  , ""  ),
  ("LooseDSAMuons"            , "dxyPVTraj"           , 20000  , -2000    , 2000  , ""  ),
  ("LooseDSAMuons"            , "dxyPVSigned"         , 10000  , 0    , 2000  , ""  ),
  ("LooseDSAMuons"            , "ip3DPVSigned"        , 20000  , -2000    , 2000  , ""  ),
  # ("LooseDSAMuons"            , "dxyBS"               , 10000  , 0    , 2000  , ""  ),
  ("LooseDSAMuons"            , "dxyBSTraj"           , 20000  , -2000    , 2000  , ""  ),
  ("LooseDSAMuons"            , "dxyBSSigned"         , 10000  , 0    , 2000  , ""  ),
  ("LooseDSAMuons"            , "ip3DBSSigned"        , 10000  , 0    , 2000  , ""  ),
  ("LooseDSAMuons"            , "muonMatch1"          , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "muonMatch1idx"       , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "muonMatch2"          , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "muonMatch2idx"       , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "muonMatch3"          , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "muonMatch3idx"       , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "muonMatch4"          , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "muonMatch4idx"       , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "muonMatch5"          , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "muonMatch5idx"       , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "outerEta"            , 300   , -3    , 3     , ""  ),
  ("LooseDSAMuons"            , "outerPhi"            , 300   , -3    , 3     , ""  ),
  ("LooseDSAMuons"            , "trkNumPlanes"        , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "trkNumHits"          , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "trkNumDTHits"        , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "trkNumCSCHits"       , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "displacedID"         , 50    , 0     , 50    , ""  ),

  ("Event"              , "nPatMuonVertex"      , 50    , 0     , 50    , ""  ),
  ("PatMuonVertex"      , "chi2"                , 500   , 0     , 500   , ""  ),
  ("PatMuonVertex"      , "vxy"                 , 10000  , -1000  , 1000   , ""  ),
  ("PatMuonVertex"      , "vxySigma"            , 10000  , -1000  , 1000   , ""  ),
  ("PatMuonVertex"      , "vz"                  , 10000  , -1000  , 1000   , ""  ),
  ("PatMuonVertex"      , "dR"                  , 500   , 0     , 10    , ""  ),
  ("PatMuonVertex"      , "idx1"                , 100   , 0     , 100   , ""  ),
  ("PatMuonVertex"      , "idx2"                , 100   , 0     , 100   , ""  ),
  ("PatMuonVertex"      , "isDSAMuon1"          , 10    , 0     , 10    , ""  ),
  ("PatMuonVertex"      , "isDSAMuon2"          , 10    , 0     , 10    , ""  ),

  ("Event"              , "nPatDSAMuonVertex"   , 50    , 0     , 50    , ""  ),
  ("PatDSAMuonVertex"   , "chi2"                , 500   , 0     , 500   , ""  ),
  ("PatDSAMuonVertex"   , "vxy"                 , 10000  , -1000  , 1000   , ""  ),
  ("PatDSAMuonVertex"   , "vxySigma"            , 10000  , -1000  , 1000   , ""  ),
  ("PatDSAMuonVertex"   , "vz"                  , 10000  , -1000  , 1000   , ""  ),
  ("PatDSAMuonVertex"   , "dR"                  , 500   , 0     , 10    , ""  ),
  ("PatDSAMuonVertex"   , "idx1"                , 100   , 0     , 100   , ""  ),
  ("PatDSAMuonVertex"   , "idx2"                , 100   , 0     , 100   , ""  ),
  ("PatDSAMuonVertex"   , "isDSAMuon1"          , 10    , 0     , 10    , ""  ),
  ("PatDSAMuonVertex"   , "isDSAMuon2"          , 10    , 0     , 10    , ""  ),

  ("Event"              , "nDSAMuonVertex"      , 50    , 0     , 50    , ""  ),
  ("DSAMuonVertex"      , "chi2"                , 500   , 0     , 500   , ""  ),
  ("DSAMuonVertex"      , "vxy"                 , 10000  , -1000  , 1000   , ""  ),
  ("DSAMuonVertex"      , "vxySigma"            , 10000  , -1000  , 1000   , ""  ),
  ("DSAMuonVertex"      , "vz"                  , 10000  , -1000  , 1000   , ""  ),
  ("DSAMuonVertex"      , "dR"                  , 500   , 0     , 10    , ""  ),
  ("DSAMuonVertex"      , "idx1"                , 100   , 0     , 100   , ""  ),
  ("DSAMuonVertex"      , "idx2"                , 100   , 0     , 100   , ""  ),
  ("DSAMuonVertex"      , "isDSAMuon1"          , 10    , 0     , 10    , ""  ),
  ("DSAMuonVertex"      , "isDSAMuon2"          , 10    , 0     , 10    , ""  ),

  # ("Event"              , "nBS"                 , 50    , 0     , 50    , ""  ),
  # ("BS"                 , "chi2"                , 500   , 0     , 500   , ""  ),
  # ("BS"                 , "ndof"                , 100   , 0     , 100   , ""  ),
  # ("BS"                 , "x"                   , 500   , 0     , 500   , ""  ),
  # ("BS"                 , "y"                   , 500   , 0     , 500   , ""  ),
  # ("BS"                 , "z"                   , 500   , 0     , 500   , ""  ),
)

if runLLPNanoAODHistograms:
  defaultHistParams = defaultHistParams + LLPNanoAOD_defaultHistParams

histParams = (
#  collection         variable                      bins   xmin   xmax    dir
  ("Muon"           , "leadingPt"                 , 2000  , 0   , 1000  , ""  ),
  ("TightMuons"     , "leadingPt"                 , 2000  , 0   , 1000  , ""  ),
  ("LooseMuons"     , "leadingPt"                 , 2000  , 0   , 1000  , ""  ),
  ("Electron"       , "leadingPt"                 , 2000  , 0   , 1000  , ""  ),
  ("LooseElectrons" , "leadingPt"                 , 2000  , 0   , 1000  , ""  ),
  ("Jet"            , "leadingPt"                 , 2000  , 0   , 1000  , ""  ),
  ("GoodJets"       , "leadingPt"                 , 2000  , 0   , 1000  , ""  ),
  
  ("Muon"           , "subleadingPt"              , 2000  , 0   , 1000  , ""  ),
  ("TightMuons"     , "subleadingPt"              , 2000  , 0   , 1000  , ""  ),
  ("LooseMuons"     , "subleadingPt"              , 2000  , 0   , 1000  , ""  ),
  ("Electron"       , "subleadingPt"              , 2000  , 0   , 1000  , ""  ),
  ("LooseElectrons" , "subleadingPt"              , 2000  , 0   , 1000  , ""  ),
  ("Jet"            , "subleadingPt"              , 2000  , 0   , 1000  , ""  ),
  ("GoodJets"       , "subleadingPt"              , 2000  , 0   , 1000  , ""  ),
  
  ("LooseMuons"     , "dimuonMinv"                , 200   , 0   , 200   , ""  ),
  ("LooseMuons"     , "dimuonMinvClosestToZ"      , 200   , 0   , 200   , ""  ),
  ("LooseMuons"     , "dimuonDeltaRclosestToZ"    , 200   , -10 , 10    , ""  ),
  ("LooseMuons"     , "dimuonDeltaEtaclosestToZ"  , 200   , -10 , 10    , ""  ),
  ("LooseMuons"     , "dimuonDeltaPhiclosestToZ"  , 200   , -10 , 10    , ""  ),
  ("GoodJets"       , "minvBjet2jets"             , 2000  , 0   , 2000  , ""  ),
  ("TightMuons"     , "deltaPhiMuonMET"           , 200   , -4  , 4     , ""  ),
  ("TightMuons"     , "minvMuonMET"               , 1000  , 0   , 1000  , ""  ),
  
  ("Event"          , "normCheck"                 , 1     , 0   , 1     , ""  ),
)

LLPNanoAOD_histParams = (
  ("Event"          , "nLooseMuonsDRMatch"   , 50    , 0     , 50    , ""  ),
  ("Event"          , "nLooseMuonsDRMatch_DSA"   , 50    , 0     , 50    , ""  ),
  ("Event"          , "nLooseMuonsDRMatch_PAT"   , 50    , 0     , 50    , ""  ),
  ("LooseMuonsDRMatch"  , "pt"               , 2000  , 0     , 1000  , ""  ),
  ("LooseMuonsDRMatch"  , "eta"              , 300   , -3    , 3     , ""  ),
  ("LooseMuonsDRMatch"  , "phi"              , 300   , -3    , 3     , ""  ),
  ("LooseMuonsDRMatch"  , "dxy"              , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsDRMatch"  , "dxyPVTraj"        , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsDRMatch"  , "dxyPVTrajErr"     , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsDRMatch"  , "dxyPVTrajSig"     , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsDRMatch"  , "dz"               , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsDRMatch"  , "dzPV"             , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsDRMatch"  , "dzPVErr"          , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsDRMatch"  , "dzPVSig"          , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsDRMatch"  , "ip3DPVSigned"     , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsDRMatch"  , "ip3DPVSignedErr"  , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsDRMatch"  , "ip3DPVSignedSig"  , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsDRMatch"  , "minDeltaR"        , 1000   , 0    , 10     , ""  ),
  ("LooseMuonsDRMatch"  , "minOuterDeltaR"   , 1000   , 0    , 10     , ""  ),
  ("LooseMuonsDRMatch"  , "minProxDeltaR"    , 1000   , 0    , 10     , ""  ),
  ("Event"          , "nLooseMuonsOuterDRMatch"   , 50    , 0     , 50    , ""  ),
  ("Event"          , "nLooseMuonsOuterDRMatch_DSA"   , 50    , 0     , 50    , ""  ),
  ("Event"          , "nLooseMuonsOuterDRMatch_PAT"   , 50    , 0     , 50    , ""  ),
  ("LooseMuonsOuterDRMatch"  , "pt"               , 2000  , 0     , 1000  , ""  ),
  ("LooseMuonsOuterDRMatch"  , "eta"              , 300   , -3    , 3     , ""  ),
  ("LooseMuonsOuterDRMatch"  , "phi"              , 300   , -3    , 3     , ""  ),
  ("LooseMuonsOuterDRMatch"  , "dxy"              , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsOuterDRMatch"  , "dxyPVTraj"        , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsOuterDRMatch"  , "dxyPVTrajErr"     , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsOuterDRMatch"  , "dxyPVTrajSig"     , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsOuterDRMatch"  , "dz"               , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsOuterDRMatch"  , "dzPV"             , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsOuterDRMatch"  , "dzPVErr"          , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsOuterDRMatch"  , "dzPVSig"          , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsOuterDRMatch"  , "ip3DPVSigned"     , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsOuterDRMatch"  , "ip3DPVSignedErr"  , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsOuterDRMatch"  , "ip3DPVSignedSig"  , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsOuterDRMatch"  , "minDeltaR"        , 1000   , 0    , 10     , ""  ),
  ("LooseMuonsOuterDRMatch"  , "minOuterDeltaR"   , 1000   , 0    , 10     , ""  ),
  ("LooseMuonsOuterDRMatch"  , "minProxDeltaR"    , 1000   , 0    , 10     , ""  ),
  ("Event"          , "nLooseMuonsSegmentMatch"   , 50    , 0     , 50    , ""  ),
  ("Event"          , "nLooseMuonsSegmentMatch_DSA"   , 50    , 0     , 50    , ""  ),
  ("Event"          , "nLooseMuonsSegmentMatch_PAT"   , 50    , 0     , 50    , ""  ),
  ("LooseMuonsSegmentMatch"  , "pt"               , 2000  , 0     , 1000  , ""  ),
  ("LooseMuonsSegmentMatch"  , "eta"              , 300   , -3    , 3     , ""  ),
  ("LooseMuonsSegmentMatch"  , "phi"              , 300   , -3    , 3     , ""  ),
  ("LooseMuonsSegmentMatch"  , "dxy"              , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsSegmentMatch"  , "dxyPVTraj"        , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsSegmentMatch"  , "dxyPVTrajErr"     , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsSegmentMatch"  , "dxyPVTrajSig"     , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsSegmentMatch"  , "dz"               , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsSegmentMatch"  , "dzPV"             , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsSegmentMatch"  , "dzPVErr"          , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsSegmentMatch"  , "dzPVSig"          , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsSegmentMatch"  , "ip3DPVSigned"     , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsSegmentMatch"  , "ip3DPVSignedErr"  , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsSegmentMatch"  , "ip3DPVSignedSig"  , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsSegmentMatch"  , "minDeltaR"        , 1000   , 0    , 10     , ""  ),
  ("LooseMuonsSegmentMatch"  , "minOuterDeltaR"   , 1000   , 0    , 10     , ""  ),
  ("LooseMuonsSegmentMatch"  , "minProxDeltaR"    , 1000   , 0    , 10     , ""  ),

  ("Event"          , "nLooseDSAMuonsSegmentMatch"   , 50    , 0     , 50    , ""  ),
  ("Event"          , "nLooseDSAMuonsSegmentMatch_DSA"   , 50    , 0     , 50    , ""  ),
  ("Event"          , "nLooseDSAMuonsSegmentMatch_PAT"   , 50    , 0     , 50    , ""  ),
  ("LooseDSAMuonsSegmentMatch"  , "pt"               , 2000  , 0     , 1000  , ""  ),
  ("LooseDSAMuonsSegmentMatch"  , "eta"              , 300   , -3    , 3     , ""  ),
  ("LooseDSAMuonsSegmentMatch"  , "phi"              , 300   , -3    , 3     , ""  ),
  ("LooseDSAMuonsSegmentMatch"  , "dxy"              , 20000  , -2000    , 2000   , ""  ),
  ("LooseDSAMuonsSegmentMatch"  , "dxyPVTraj"        , 20000  , -2000    , 2000   , ""  ),
  ("LooseDSAMuonsSegmentMatch"  , "dxyPVTrajErr"     , 10000  , 0    , 2000   , ""  ),
  ("LooseDSAMuonsSegmentMatch"  , "dxyPVTrajSig"     , 10000  , 0    , 2000   , ""  ),
  ("LooseDSAMuonsSegmentMatch"  , "dz"               , 20000  , -2000    , 2000   , ""  ),
  ("LooseDSAMuonsSegmentMatch"  , "dzPV"             , 20000  , -2000    , 2000   , ""  ),
  ("LooseDSAMuonsSegmentMatch"  , "dzPVErr"          , 10000  , 0    , 2000   , ""  ),
  ("LooseDSAMuonsSegmentMatch"  , "dzPVSig"          , 10000  , 0    , 2000   , ""  ),
  ("LooseDSAMuonsSegmentMatch"  , "ip3DPVSigned"     , 20000  , -2000    , 2000   , ""  ),
  ("LooseDSAMuonsSegmentMatch"  , "ip3DPVSignedErr"  , 10000  , 0    , 2000   , ""  ),
  ("LooseDSAMuonsSegmentMatch"  , "ip3DPVSignedSig"  , 10000  , 0    , 2000   , ""  ),
  ("Event"          , "nLoosePATMuonsSegmentMatch"   , 50    , 0     , 50    , ""  ),
  ("Event"          , "nLoosePATMuonsSegmentMatch_DSA"   , 50    , 0     , 50    , ""  ),
  ("Event"          , "nLoosePATMuonsSegmentMatch_PAT"   , 50    , 0     , 50    , ""  ),
  ("LoosePATMuonsSegmentMatch"  , "pt"               , 2000  , 0     , 1000  , ""  ),
  ("LoosePATMuonsSegmentMatch"  , "eta"              , 300   , -3    , 3     , ""  ),
  ("LoosePATMuonsSegmentMatch"  , "phi"              , 300   , -3    , 3     , ""  ),
  ("LoosePATMuonsSegmentMatch"  , "dxy"              , 20000  , -2000    , 2000   , ""  ),
  ("LoosePATMuonsSegmentMatch"  , "dxyPVTraj"        , 20000  , -2000    , 2000   , ""  ),
  ("LoosePATMuonsSegmentMatch"  , "dxyPVTrajErr"     , 10000  , 0    , 2000   , ""  ),
  ("LoosePATMuonsSegmentMatch"  , "dxyPVTrajSig"     , 10000  , 0    , 2000   , ""  ),
  ("LoosePATMuonsSegmentMatch"  , "dz"               , 20000  , -2000    , 2000   , ""  ),
  ("LoosePATMuonsSegmentMatch"  , "dzPV"             , 20000  , -2000    , 2000   , ""  ),
  ("LoosePATMuonsSegmentMatch"  , "dzPVErr"          , 10000  , 0    , 2000   , ""  ),
  ("LoosePATMuonsSegmentMatch"  , "dzPVSig"          , 10000  , 0    , 2000   , ""  ),
  ("LoosePATMuonsSegmentMatch"  , "ip3DPVSigned"     , 20000  , -2000    , 2000   , ""  ),
  ("LoosePATMuonsSegmentMatch"  , "ip3DPVSignedErr"  , 10000  , 0    , 2000   , ""  ),
  ("LoosePATMuonsSegmentMatch"  , "ip3DPVSignedSig"  , 10000  , 0    , 2000   , ""  ),
  ("Event"          , "nLooseDSAMuonsOuterDRMatch"   , 50    , 0     , 50    , ""  ),
  ("Event"          , "nLooseDSAMuonsOuterDRMatch_DSA"   , 50    , 0     , 50    , ""  ),
  ("Event"          , "nLooseDSAMuonsOuterDRMatch_PAT"   , 50    , 0     , 50    , ""  ),
  ("LooseDSAMuonsOuterDRMatch"  , "pt"               , 2000  , 0     , 1000  , ""  ),
  ("LooseDSAMuonsOuterDRMatch"  , "eta"              , 300   , -3    , 3     , ""  ),
  ("LooseDSAMuonsOuterDRMatch"  , "phi"              , 300   , -3    , 3     , ""  ),
  ("LooseDSAMuonsOuterDRMatch"  , "dxy"              , 20000  , -2000    , 2000   , ""  ),
  ("LooseDSAMuonsOuterDRMatch"  , "dxyPVTraj"        , 20000  , -2000    , 2000   , ""  ),
  ("LooseDSAMuonsOuterDRMatch"  , "dxyPVTrajErr"     , 10000  , 0    , 2000   , ""  ),
  ("LooseDSAMuonsOuterDRMatch"  , "dxyPVTrajSig"     , 10000  , 0    , 2000   , ""  ),
  ("LooseDSAMuonsOuterDRMatch"  , "dz"               , 20000  , -2000    , 2000   , ""  ),
  ("LooseDSAMuonsOuterDRMatch"  , "dzPV"             , 20000  , -2000    , 2000   , ""  ),
  ("LooseDSAMuonsOuterDRMatch"  , "dzPVErr"          , 10000  , 0    , 2000   , ""  ),
  ("LooseDSAMuonsOuterDRMatch"  , "dzPVSig"          , 10000  , 0    , 2000   , ""  ),
  ("LooseDSAMuonsOuterDRMatch"  , "ip3DPVSigned"     , 20000  , -2000    , 2000   , ""  ),
  ("LooseDSAMuonsOuterDRMatch"  , "ip3DPVSignedErr"  , 10000  , 0    , 2000   , ""  ),
  ("LooseDSAMuonsOuterDRMatch"  , "ip3DPVSignedSig"  , 10000  , 0    , 2000   , ""  ),
  ("Event"          , "nLoosePATMuonsOuterDRMatch"   , 50    , 0     , 50    , ""  ),
  ("Event"          , "nLoosePATMuonsOuterDRMatch_DSA"   , 50    , 0     , 50    , ""  ),
  ("Event"          , "nLoosePATMuonsOuterDRMatch_PAT"   , 50    , 0     , 50    , ""  ),
  ("LoosePATMuonsOuterDRMatch"  , "pt"               , 2000  , 0     , 1000  , ""  ),
  ("LoosePATMuonsOuterDRMatch"  , "eta"              , 300   , -3    , 3     , ""  ),
  ("LoosePATMuonsOuterDRMatch"  , "phi"              , 300   , -3    , 3     , ""  ),
  ("LoosePATMuonsOuterDRMatch"  , "dxy"              , 20000  , -2000    , 2000   , ""  ),
  ("LoosePATMuonsOuterDRMatch"  , "dxyPVTraj"        , 20000  , -2000    , 2000   , ""  ),
  ("LoosePATMuonsOuterDRMatch"  , "dxyPVTrajErr"     , 10000  , 0    , 2000   , ""  ),
  ("LoosePATMuonsOuterDRMatch"  , "dxyPVTrajSig"     , 10000  , 0    , 2000   , ""  ),
  ("LoosePATMuonsOuterDRMatch"  , "dz"               , 20000  , -2000    , 2000   , ""  ),
  ("LoosePATMuonsOuterDRMatch"  , "dzPV"             , 20000  , -2000    , 2000   , ""  ),
  ("LoosePATMuonsOuterDRMatch"  , "dzPVErr"          , 10000  , 0    , 2000   , ""  ),
  ("LoosePATMuonsOuterDRMatch"  , "dzPVSig"          , 10000  , 0    , 2000   , ""  ),
  ("LoosePATMuonsOuterDRMatch"  , "ip3DPVSigned"     , 20000  , -2000    , 2000   , ""  ),
  ("LoosePATMuonsOuterDRMatch"  , "ip3DPVSignedErr"  , 10000  , 0    , 2000   , ""  ),
  ("LoosePATMuonsOuterDRMatch"  , "ip3DPVSignedSig"  , 10000  , 0    , 2000   , ""  ),

  # ("Event"          , "nLooseMuonsVertexDRMatch"        , 50     , 0      , 50     , ""  ),
  # ("LooseMuonsVertexDRMatch" , "chi2"                   , 500    , 0      , 500    , ""  ),
  # ("LooseMuonsVertexDRMatch" , "ndof"                   , 500    , 0      , 500    , ""  ),
  # ("LooseMuonsVertexDRMatch" , "normChi2"                   , 500    , 0      , 500    , ""  ),
  # ("LooseMuonsVertexDRMatch" , "vxy"                    , 10000  , -1000  , 1000   , ""  ),
  # ("LooseMuonsVertexDRMatch" , "vxySigma"               , 10000  , -1000  , 1000   , ""  ),
  # ("LooseMuonsVertexDRMatch" , "vxyz"                   , 10000  , -1000  , 1000   , ""  ),
  # ("LooseMuonsVertexDRMatch" , "vx"                     , 10000  , -1000  , 1000   , ""  ),
  # ("LooseMuonsVertexDRMatch" , "vy"                     , 10000  , -1000  , 1000   , ""  ),
  # ("LooseMuonsVertexDRMatch" , "vz"                     , 10000  , -1000  , 1000   , ""  ),
  # ("LooseMuonsVertexDRMatch" , "dR"                     , 500    , 0      , 10     , ""  ),
  # ("LooseMuonsVertexDRMatch" , "proxDR"                 , 500    , 0      , 10     , ""  ),
  # ("LooseMuonsVertexDRMatch" , "idx1"                   , 100    , 0      , 100    , ""  ),
  # ("LooseMuonsVertexDRMatch" , "idx2"                   , 100    , 0      , 100    , ""  ),
  # ("LooseMuonsVertexDRMatch" , "isDSAMuon1"             , 10     , 0      , 10     , ""  ),
  # ("LooseMuonsVertexDRMatch" , "isDSAMuon2"             , 10     , 0      , 10     , ""  ),
  # ("LooseMuonsVertexDRMatch" , "displacedTrackIso03Dimuon1"   , 5000  , 0     , 500    , ""  ),
  # ("LooseMuonsVertexDRMatch" , "displacedTrackIso04Dimuon1"   , 5000  , 0     , 500    , ""  ),
  # ("LooseMuonsVertexDRMatch" , "displacedTrackIso03Dimuon2"   , 5000  , 0     , 500    , ""  ),
  # ("LooseMuonsVertexDRMatch" , "displacedTrackIso04Dimuon2"   , 5000  , 0     , 500    , ""  ),
  # ("LooseMuonsVertexDRMatch" , "displacedTrackIso03Muon1"     , 5000  , 0     , 500    , ""  ),
  # ("LooseMuonsVertexDRMatch" , "displacedTrackIso04Muon1"     , 5000  , 0     , 500    , ""  ),
  # ("LooseMuonsVertexDRMatch" , "displacedTrackIso03Muon2"     , 5000  , 0     , 500    , ""  ),
  # ("LooseMuonsVertexDRMatch" , "displacedTrackIso04Muon2"     , 5000  , 0     , 500    , ""  ),
  # ("Event"          , "nLooseMuonsVertexDRMatch_PatDSA", 50    , 0     , 50    , ""  ),
  # ("LooseMuonsVertexDRMatch_PatDSA" , "chi2"           , 500   , 0     , 500   , ""  ),
  # ("LooseMuonsVertexDRMatch_PatDSA" , "vxy"            , 10000  , -1000  , 1000   , ""  ),
  # ("LooseMuonsVertexDRMatch_PatDSA" , "vxySigma"       , 10000  , -1000  , 1000   , ""  ),
  # ("LooseMuonsVertexDRMatch_PatDSA" , "vxyz"           , 10000  , -1000  , 1000   , ""  ),
  # ("LooseMuonsVertexDRMatch_PatDSA" , "vx"             , 10000  , -1000  , 1000   , ""  ),
  # ("LooseMuonsVertexDRMatch_PatDSA" , "vy"             , 10000  , -1000  , 1000   , ""  ),
  # ("LooseMuonsVertexDRMatch_PatDSA" , "vz"             , 10000  , -1000  , 1000   , ""  ),
  # ("LooseMuonsVertexDRMatch_PatDSA" , "dR"             , 500   , 0     , 10    , ""  ),
  # ("LooseMuonsVertexDRMatch_PatDSA" , "proxDR"         , 500   , 0     , 10    , ""  ),
  # ("Event"          , "nLooseMuonsVertexDRMatch_Pat"   , 50    , 0     , 50    , ""  ),
  # ("LooseMuonsVertexDRMatch_Pat"    , "chi2"           , 500   , 0     , 500   , ""  ),
  # ("LooseMuonsVertexDRMatch_Pat"    , "vxy"            , 10000  , -1000  , 1000   , ""  ),
  # ("LooseMuonsVertexDRMatch_Pat"    , "vxySigma"       , 10000  , -1000  , 1000   , ""  ),
  # ("LooseMuonsVertexDRMatch_Pat"    , "vxyz"           , 10000  , -1000  , 1000   , ""  ),
  # ("LooseMuonsVertexDRMatch_Pat"    , "vx"             , 10000  , -1000  , 1000   , ""  ),
  # ("LooseMuonsVertexDRMatch_Pat"    , "vy"             , 10000  , -1000  , 1000   , ""  ),
  # ("LooseMuonsVertexDRMatch_Pat"    , "vz"             , 10000  , -1000  , 1000   , ""  ),
  # ("LooseMuonsVertexDRMatch_Pat"    , "dR"             , 500   , 0     , 10    , ""  ),
  # ("LooseMuonsVertexDRMatch_Pat"    , "proxDR"         , 500   , 0     , 10    , ""  ),
  # ("Event"          , "nLooseMuonsVertexDRMatch_DSA"   , 50    , 0     , 50    , ""  ),
  # ("LooseMuonsVertexDRMatch_DSA"    , "chi2"           , 500   , 0     , 500   , ""  ),
  # ("LooseMuonsVertexDRMatch_DSA"    , "vxy"            , 10000  , -1000  , 1000   , ""  ),
  # ("LooseMuonsVertexDRMatch_DSA"    , "vxySigma"       , 10000  , -1000  , 1000   , ""  ),
  # ("LooseMuonsVertexDRMatch_DSA"    , "vxyz"           , 10000  , -1000  , 1000   , ""  ),
  # ("LooseMuonsVertexDRMatch_DSA"    , "vx"           , 10000  , -1000  , 1000   , ""  ),
  # ("LooseMuonsVertexDRMatch_DSA"    , "vy"           , 10000  , -1000  , 1000   , ""  ),
  # ("LooseMuonsVertexDRMatch_DSA"    , "vz"             , 10000  , -1000  , 1000   , ""  ),
  # ("LooseMuonsVertexDRMatch_DSA"    , "dR"             , 500   , 0     , 10    , ""  ),
  # ("LooseMuonsVertexDRMatch_DSA"    , "proxDR"         , 500   , 0     , 10    , ""  ),
  
  ("Event"          , "nLooseMuonsVertexOuterDRMatch"       , 50     , 0      , 50     , ""  ),
  ("LooseMuonsVertexOuterDRMatch" , "chi2"                  , 500    , 0      , 500    , ""  ),
  ("LooseMuonsVertexOuterDRMatch" , "ndof"                  , 500    , 0      , 500    , ""  ),
  ("LooseMuonsVertexOuterDRMatch" , "normChi2"              , 500    , 0      , 500    , ""  ),
  ("LooseMuonsVertexOuterDRMatch" , "vxy"                   , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexOuterDRMatch" , "vxySigma"              , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexOuterDRMatch" , "vx"                    , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexOuterDRMatch" , "vy"                    , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexOuterDRMatch" , "vz"                    , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexOuterDRMatch" , "vxyz"                  , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexOuterDRMatch" , "dR"                    , 500    , 0      , 10     , ""  ),
  ("LooseMuonsVertexOuterDRMatch" , "proxDR"                , 500    , 0      , 10     , ""  ),
  ("LooseMuonsVertexOuterDRMatch" , "idx1"                  , 100    , 0      , 100    , ""  ),
  ("LooseMuonsVertexOuterDRMatch" , "idx2"                  , 100    , 0      , 100    , ""  ),
  ("LooseMuonsVertexOuterDRMatch" , "isDSAMuon1"            , 10     , 0      , 10     , ""  ),
  ("LooseMuonsVertexOuterDRMatch" , "isDSAMuon2"            , 10     , 0      , 10     , ""  ),
  ("LooseMuonsVertexOuterDRMatch" , "displacedTrackIso03Dimuon1"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsVertexOuterDRMatch" , "displacedTrackIso04Dimuon1"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsVertexOuterDRMatch" , "displacedTrackIso03Dimuon2"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsVertexOuterDRMatch" , "displacedTrackIso04Dimuon2"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsVertexOuterDRMatch" , "displacedTrackIso03Muon1"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsVertexOuterDRMatch" , "displacedTrackIso04Muon1"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsVertexOuterDRMatch" , "displacedTrackIso03Muon2"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsVertexOuterDRMatch" , "displacedTrackIso04Muon2"     , 5000  , 0     , 500    , ""  ),
  ("Event"          , "nLooseMuonsVertexOuterDRMatch_PatDSA", 50     , 0      , 50     , ""  ),
  ("LooseMuonsVertexOuterDRMatch_PatDSA" , "chi2"           , 500    , 0      , 500    , ""  ),
  ("LooseMuonsVertexOuterDRMatch_PatDSA" , "vxy"            , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexOuterDRMatch_PatDSA" , "vxySigma"       , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexOuterDRMatch_PatDSA" , "vx"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexOuterDRMatch_PatDSA" , "vy"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexOuterDRMatch_PatDSA" , "vz"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexOuterDRMatch_PatDSA" , "vxyz"           , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexOuterDRMatch_PatDSA" , "dR"             , 500    , 0      , 10     , ""  ),
  ("LooseMuonsVertexOuterDRMatch_PatDSA" , "proxDR"         , 500    , 0      , 10     , ""  ),
  ("Event"          , "nLooseMuonsVertexOuterDRMatch_Pat"   , 50     , 0      , 50     , ""  ),
  ("LooseMuonsVertexOuterDRMatch_Pat"    , "chi2"           , 500    , 0      , 500    , ""  ),
  ("LooseMuonsVertexOuterDRMatch_Pat"    , "vxy"            , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexOuterDRMatch_Pat"    , "vxySigma"       , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexOuterDRMatch_Pat"    , "vx"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexOuterDRMatch_Pat"    , "vy"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexOuterDRMatch_Pat"    , "vz"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexOuterDRMatch_Pat"    , "vxyz"           , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexOuterDRMatch_Pat"    , "dR"             , 500    , 0      , 10     , ""  ),
  ("LooseMuonsVertexOuterDRMatch_Pat"    , "proxDR"         , 500    , 0      , 10     , ""  ),
  ("Event"          , "nLooseMuonsVertexOuterDRMatch_DSA"   , 50     , 0      , 50     , ""  ),
  ("LooseMuonsVertexOuterDRMatch_DSA"    , "chi2"           , 500    , 0      , 500    , ""  ),
  ("LooseMuonsVertexOuterDRMatch_DSA"    , "vxy"            , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexOuterDRMatch_DSA"    , "vxySigma"       , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexOuterDRMatch_DSA"    , "vxyz"           , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexOuterDRMatch_DSA"    , "vx"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexOuterDRMatch_DSA"    , "vy"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexOuterDRMatch_DSA"    , "vz"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexOuterDRMatch_DSA"    , "dR"             , 500    , 0      , 10     , ""  ),
  ("LooseMuonsVertexOuterDRMatch_DSA"    , "proxDR"         , 500    , 0      , 10     , ""  ),

  ("Event"          , "nLooseMuonsVertexSegmentMatch"       , 50     , 0      , 50     , ""  ),
  ("LooseMuonsVertexSegmentMatch" , "chi2"                  , 500    , 0      , 500    , ""  ),
  ("LooseMuonsVertexSegmentMatch" , "ndof"                  , 500    , 0      , 500    , ""  ),
  ("LooseMuonsVertexSegmentMatch" , "normChi2"              , 500    , 0      , 500    , ""  ),
  ("LooseMuonsVertexSegmentMatch" , "vxy"                   , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexSegmentMatch" , "vxySigma"              , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexSegmentMatch" , "vx"                    , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexSegmentMatch" , "vy"                    , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexSegmentMatch" , "vz"                    , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexSegmentMatch" , "vxyz"                  , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexSegmentMatch" , "dR"                    , 500    , 0      , 10     , ""  ),
  ("LooseMuonsVertexSegmentMatch" , "proxDR"                , 500    , 0      , 10     , ""  ),
  ("LooseMuonsVertexSegmentMatch" , "idx1"                  , 100    , 0      , 100    , ""  ),
  ("LooseMuonsVertexSegmentMatch" , "idx2"                  , 100    , 0      , 100    , ""  ),
  ("LooseMuonsVertexSegmentMatch" , "isDSAMuon1"            , 10     , 0      , 10     , ""  ),
  ("LooseMuonsVertexSegmentMatch" , "isDSAMuon2"            , 10     , 0      , 10     , ""  ),
  ("LooseMuonsVertexSegmentMatch" , "displacedTrackIso03Dimuon1"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsVertexSegmentMatch" , "displacedTrackIso04Dimuon1"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsVertexSegmentMatch" , "displacedTrackIso03Dimuon2"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsVertexSegmentMatch" , "displacedTrackIso04Dimuon2"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsVertexSegmentMatch" , "displacedTrackIso03Muon1"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsVertexSegmentMatch" , "displacedTrackIso04Muon1"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsVertexSegmentMatch" , "displacedTrackIso03Muon2"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsVertexSegmentMatch" , "displacedTrackIso04Muon2"     , 5000  , 0     , 500    , ""  ),
  ("Event"          , "nLooseMuonsVertexSegmentMatch_PatDSA", 50    , 0     , 50    , ""  ),
  ("LooseMuonsVertexSegmentMatch_PatDSA" , "chi2"           , 500   , 0     , 500   , ""  ),
  ("LooseMuonsVertexSegmentMatch_PatDSA" , "vxy"            , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexSegmentMatch_PatDSA" , "vxySigma"       , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexSegmentMatch_PatDSA" , "vxyz"           , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexSegmentMatch_PatDSA" , "vx"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexSegmentMatch_PatDSA" , "vy"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexSegmentMatch_PatDSA" , "vz"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexSegmentMatch_PatDSA" , "dR"             , 500   , 0     , 10    , ""  ),
  ("LooseMuonsVertexSegmentMatch_PatDSA" , "proxDR"         , 500   , 0     , 10    , ""  ),
  ("Event"          , "nLooseMuonsVertexSegmentMatch_Pat"   , 50    , 0     , 50    , ""  ),
  ("LooseMuonsVertexSegmentMatch_Pat"    , "chi2"           , 500   , 0     , 500   , ""  ),
  ("LooseMuonsVertexSegmentMatch_Pat"    , "vxy"            , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexSegmentMatch_Pat"    , "vxySigma"       , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexSegmentMatch_Pat"    , "vxyz"           , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexSegmentMatch_Pat"    , "vx"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexSegmentMatch_Pat"    , "vy"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexSegmentMatch_Pat"    , "vz"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexSegmentMatch_Pat"    , "dR"             , 500   , 0     , 10    , ""  ),
  ("LooseMuonsVertexSegmentMatch_Pat"    , "proxDR"         , 500   , 0     , 10    , ""  ),
  ("Event"          , "nLooseMuonsVertexSegmentMatch_DSA"   , 50    , 0     , 50    , ""  ),
  ("LooseMuonsVertexSegmentMatch_DSA"    , "chi2"           , 500   , 0     , 500   , ""  ),
  ("LooseMuonsVertexSegmentMatch_DSA"    , "vxy"            , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexSegmentMatch_DSA"    , "vxySigma"       , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexSegmentMatch_DSA"    , "vxyz"           , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexSegmentMatch_DSA"    , "vx"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexSegmentMatch_DSA"    , "vy"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexSegmentMatch_DSA"    , "vz"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsVertexSegmentMatch_DSA"    , "dR"             , 500   , 0     , 10    , ""  ),
  ("LooseMuonsVertexSegmentMatch_DSA"    , "proxDR"         , 500   , 0     , 10    , ""  ),
)

MuonMatching_histParams = (
  ("Event"             , "nSegmentMatchLooseMuons"          , 50    , 0     , 50    , ""  ),
  ("SegmentMatchLooseMuons"  , "genMinDR"                   , 1000  , 0     , 10    , ""  ),
  ("SegmentMatchLooseMuons"  , "genMinDRidx"                , 100   , 0     , 100   , ""  ),
  ("SegmentMatchLooseMuons"  , "nSegments"                  , 50    , 0     , 50    , ""  ),
  ("SegmentMatchLooseMuons"  , "matchingRatio"              , 600   , 0     , 2     , ""  ),
  ("SegmentMatchLooseMuons"  , "maxMatches"                 , 50    , 0     , 50    , ""  ),
  ("SegmentMatchLooseMuons"  , "muonMatchIdx"               , 50    , 0     , 50    , ""  ),
  ("SegmentMatchLooseMuons"  , "pt"                         , 2000  , 0     , 1000  , ""  ),
  ("SegmentMatchLooseMuons"  , "eta"                        , 300   , -3    , 3     , ""  ),
  ("SegmentMatchLooseMuons"  , "phi"                        , 300   , -3    , 3     , ""  ),
  ("SegmentMatchLooseMuons"  , "dxy"                        , 20000  , -2000    , 2000   , ""  ),
  ("SegmentMatchLooseMuons"  , "dxyPVTraj"                  , 20000  , -2000    , 2000   , ""  ),
  ("SegmentMatchLooseMuons"  , "dxyPVTrajSig"               , 10000  , 0    , 2000   , ""  ),
  ("SegmentMatchLooseMuons"  , "dzPV"                       , 20000  , -2000    , 2000   , ""  ),
  ("SegmentMatchLooseMuons"  , "dzPVSig"                    , 10000  , 0    , 2000   , ""  ),
  ("SegmentMatchLooseMuons"  , "ip3DPVSigned"               , 20000  , -2000    , 2000   , ""  ),
  ("SegmentMatchLooseMuons"  , "ip3DPVSignedSig"            , 10000  , 0    , 2000   , ""  ),

  ("Event"             , "nSegmentMatchLooseDSAMuons"       , 50    , 0     , 50    , ""  ),
  ("SegmentMatchLooseDSAMuons"  , "genMinDR"                , 1000  , 0     , 10    , ""  ),
  ("SegmentMatchLooseDSAMuons"  , "genMinDRidx"             , 100   , 0     , 100   , ""  ),
  ("SegmentMatchLooseDSAMuons"  , "pt"                      , 2000  , 0     , 1000  , ""  ),
  ("SegmentMatchLooseDSAMuons"  , "eta"                     , 300   , -3    , 3     , ""  ),
  ("SegmentMatchLooseDSAMuons"  , "phi"                     , 300   , -3    , 3     , ""  ),
  ("SegmentMatchLooseDSAMuons"  , "dxy"                     , 20000  , -2000    , 2000   , ""  ),
  ("SegmentMatchLooseDSAMuons"  , "dxyPVTraj"               , 20000  , -2000    , 2000   , ""  ),
  ("SegmentMatchLooseDSAMuons"  , "dxyPVTrajSig"            , 10000  , 0    , 2000   , ""  ),
  ("SegmentMatchLooseDSAMuons"  , "dzPV"                    , 20000  , -2000    , 2000   , ""  ),
  ("SegmentMatchLooseDSAMuons"  , "dzPVSig"                 , 10000  , 0    , 2000   , ""  ),
  ("SegmentMatchLooseDSAMuons"  , "ip3DPVSigned"            , 20000  , -2000    , 2000   , ""  ),
  ("SegmentMatchLooseDSAMuons"  , "ip3DPVSignedSig"         , 10000  , 0    , 2000   , ""  ),
  
  ("Event"             , "nSegmentDRMatchLooseMuons"        , 50    , 0     , 50    , ""  ),
  ("SegmentDRMatchLooseMuons"  , "nSegments"                 , 50    , 0     , 50    , ""  ),
  ("SegmentDRMatchLooseMuons"  , "matchingRatio"            , 600   , 0     , 2     , ""  ),
  ("SegmentDRMatchLooseMuons"  , "maxMatches"               , 50    , 0     , 50    , ""  ),
  ("SegmentDRMatchLooseMuons"  , "muonMatchIdx"               , 50    , 0     , 50    , ""  ),
  ("SegmentDRMatchLooseMuons"  , "pt"                       , 2000  , 0     , 1000  , ""  ),
  ("SegmentDRMatchLooseMuons"  , "eta"                      , 300   , -3    , 3     , ""  ),
  ("SegmentDRMatchLooseMuons"  , "phi"                      , 300   , -3    , 3     , ""  ),
  ("SegmentDRMatchLooseMuons"  , "dxy"                      , 20000  , -2000    , 2000   , ""  ),
  ("SegmentDRMatchLooseMuons"  , "dxyPVTraj"                , 20000  , -2000    , 2000   , ""  ),
  ("SegmentDRMatchLooseMuons"  , "dxyPVTrajSig"             , 10000  , 0    , 2000   , ""  ),
  ("SegmentDRMatchLooseMuons"  , "dzPV"                     , 20000  , -2000    , 2000   , ""  ),
  ("SegmentDRMatchLooseMuons"  , "dzPVSig"                  , 10000  , 0    , 2000   , ""  ),
  ("SegmentDRMatchLooseMuons"  , "ip3DPVSigned"             , 20000  , -2000    , 2000   , ""  ),
  ("SegmentDRMatchLooseMuons"  , "ip3DPVSignedSig"          , 10000  , 0    , 2000   , ""  ),
  ("Event"             , "nSegmentOuterDRMatchLooseMuons"   , 50    , 0     , 50    , ""  ),
  ("SegmentOuterDRMatchLooseMuons"  , "nSegments"           , 50    , 0     , 50    , ""  ),
  ("SegmentOuterDRMatchLooseMuons"  , "matchingRatio"       , 600   , 0     , 2     , ""  ),
  ("SegmentOuterDRMatchLooseMuons"  , "maxMatches"          , 50    , 0     , 50    , ""  ),
  ("SegmentOuterDRMatchLooseMuons"  , "muonMatchIdx"               , 50    , 0     , 50    , ""  ),
  ("SegmentOuterDRMatchLooseMuons"  , "pt"                  , 2000  , 0     , 1000  , ""  ),
  ("SegmentOuterDRMatchLooseMuons"  , "eta"                 , 300   , -3    , 3     , ""  ),
  ("SegmentOuterDRMatchLooseMuons"  , "phi"                 , 300   , -3    , 3     , ""  ),
  ("SegmentOuterDRMatchLooseMuons"  , "dxy"                 , 20000  , -2000    , 2000   , ""  ),
  ("SegmentOuterDRMatchLooseMuons"  , "dxyPVTraj"           , 20000  , -2000    , 2000   , ""  ),
  ("SegmentOuterDRMatchLooseMuons"  , "dxyPVTrajSig"        , 10000  , 0    , 2000   , ""  ),
  ("SegmentOuterDRMatchLooseMuons"  , "dzPV"                , 20000  , -2000    , 2000   , ""  ),
  ("SegmentOuterDRMatchLooseMuons"  , "dzPVSig"             , 10000  , 0    , 2000   , ""  ),
  ("SegmentOuterDRMatchLooseMuons"  , "ip3DPVSigned"        , 20000  , -2000    , 2000   , ""  ),
  ("SegmentOuterDRMatchLooseMuons"  , "ip3DPVSignedSig"     , 10000  , 0    , 2000   , ""  ),

  ("LooseDSAMuons"  , "nSegments"              , 50  , 0    , 50   , ""  ),
  ("LooseDSAMuons"  , "nDTHits"                , 50    , 0     , 50    , ""  ),
  ("LooseDSAMuons"  , "nCSCHits"               , 50    , 0     , 50    , ""  ),
  ("LooseDSAMuons"  , "nDTplusCSCHits"         , 50    , 0     , 50    , ""  ),
  ("LooseDSAMuons"  , "muonMatch1"             , 50    , 0     , 50    , ""  ),
  ("LooseDSAMuons"  , "muonMatch2"             , 50    , 0     , 50    , ""  ),
  ("LooseDSAMuons"  , "muonMatch3"             , 50    , 0     , 50    , ""  ),
  ("LooseDSAMuons"  , "matchRatio1"            , 600   , 0     , 2     , ""  ),
  ("LooseDSAMuons"  , "matchRatio2"            , 600   , 0     , 2     , ""  ),
  ("LooseDSAMuons"  , "matchRatio3"            , 600   , 0     , 2     , ""  ),

  ("LooseDSAMuons"  , "PATOuterDR"             , 1000  , 0     , 10    , ""  ),
  ("LooseDSAMuons"  , "PATProxDR"              , 1000  , 0     , 10    , ""  ),
  ("LooseDSAMuons"  , "PATDR"                  , 1000  , 0     , 10    , ""  ),
  ("LooseDSAMuons"  , "PATDEta"                , 600   , -6    , 6     , ""  ),
  ("LooseDSAMuons"  , "PATDPhi"                , 600   , -6    , 6     , ""  ),
  ("LooseDSAMuons"  , "PATDOuterEta"           , 600   , -6    , 6     , ""  ),
  ("LooseDSAMuons"  , "PATDOuterPhi"           , 600   , -6    , 6     , ""  ),
)

GenMuon_histParams = (
  ("Event"                     , "nGenMuonFromALP" , 50    , 0     , 50    , ""  ),
  ("GenMuonFromALP"            , "pdgId"           , 200   , -100  , 100   , ""  ),
  ("GenMuonFromALP"            , "pt"              , 4000  , 0     , 1000  , ""  ),
  ("GenMuonFromALP"            , "mass"            , 10000 , 0     , 100   , ""  ),
  ("GenMuonFromALP"            , "eta"             , 300   , -3    , 3     , ""  ),
  ("GenMuonFromALP"            , "phi"             , 300   , -3    , 3     , ""  ),
  ("GenMuonFromALP"            , "vx"              , 50000 , -5000 , 5000  , ""  ),
  ("GenMuonFromALP"            , "vy"              , 50000 , -5000 , 5000  , ""  ),
  ("GenMuonFromALP"            , "vz"              , 50000 , -5000 , 5000  , ""  ),
  ("GenMuonFromALP"            , "vxy"             , 50000 , 0     , 5000  , ""  ),
  ("GenMuonFromALP"            , "vxyz"            , 50000 , 0     , 5000  , ""  ),
  ("GenMuonFromALP"            , "boost"           , 2000 , 0      , 1000  , ""  ),
  ("GenMuonFromALP"            , "vxyALPboostpT"   , 50000 , 0     , 5000  , ""  ),
  ("GenMuonFromALP"            , "vxyALPboostT"    , 50000 , 0     , 5000  , ""  ),
  ("GenMuonFromALP"            , "vxyzALPboostp"   , 50000 , 0     , 5000  , ""  ),
  ("GenMuonFromALP"            , "dxy"             , 50000 , -5000 , 5000  , ""  ),
  ("GenMuonFromALP"            , "looseMuonsMinDR"             , 1000  , 0     , 10    , ""  ),
  ("GenMuonFromALP"            , "looseDSAMuonsMinDR"          , 1000  , 0     , 10    , ""  ),
  ("GenMuonFromALP"            , "looseMuonsDRMatchMinDR"      , 1000  , 0     , 10    , ""  ),
  ("GenMuonFromALP"            , "looseMuonsOuterDRMatchMinDR" , 1000  , 0     , 10    , ""  ),
  ("GenMuonFromALP"            , "looseMuonsSegmentMatchMinDR" , 1000  , 0     , 10    , ""  ),
  ("Event"                     , "nGenDimuonFromALP" , 50  , 0     , 50    , ""  ),
  ("GenDimuonFromALP"          , "invMass"         , 10000 , 0     , 100   , ""  ),
  ("GenDimuonFromALP"          , "deltaR"          , 1000  , 0     , 10    , ""  ),
  ("GenDimuonFromALP"          , "deltaEta"        , 300   , -3    , 3     , ""  ),
  ("GenDimuonFromALP"          , "deltaPhi"        , 300   , -3    , 3     , ""  ),
  ("Event"                     , "nGenALP"         , 50    , 0     , 50    , ""  ),
  ("GenALP"                    , "pdgId"           , 200   , -100  , 100   , ""  ),
  ("GenALP"                    , "pt"              , 4000  , 0     , 1000  , ""  ),
  ("GenALP"                    , "mass"            , 10000 , 0     , 100   , ""  ),
  ("GenALP"                    , "massT"           , 10000 , 0     , 100   , ""  ),
  ("GenALP"                    , "eta"             , 300   , -3    , 3     , ""  ),
  ("GenALP"                    , "phi"             , 300   , -3    , 3     , ""  ),
  ("GenALP"                    , "vx"              , 10000 , -1000 , 1000  , ""  ),
  ("GenALP"                    , "vy"              , 10000 , -1000 , 1000  , ""  ),
  ("GenALP"                    , "vz"              , 10000 , -1000 , 1000  , ""  ),
  ("GenALP"                    , "vxy"             , 10000 , -1000 , 1000  , ""  ),
  ("GenALP"                    , "vxyz"            , 10000 , -1000 , 1000  , ""  ),
  ("GenALP"                    , "boost_pT"        , 2000 , 0      , 1000  , ""  ),
  ("GenALP"                    , "boost_p"         , 2000 , 0      , 1000  , ""  ),
  ("GenALP"                    , "boost_T"         , 2000 , 0      , 1000  , ""  ),
  ("GenALP"                    , "dxy"             , 10000 , -1000 , 1000  , ""  ),
  
  ("Event"          , "nLooseMuonsFromALPDRMatch"        , 50    , 0     , 50    , ""  ),
  ("Event"          , "nLooseMuonsFromALPDRMatch_DSA"    , 50    , 0     , 50    , ""  ),
  ("Event"          , "nLooseMuonsFromALPDRMatch_PAT"    , 50    , 0     , 50    , ""  ),
  ("LooseMuonsFromALPDRMatch"       , "pt"               , 2000  , 0     , 1000  , ""  ),
  ("LooseMuonsFromALPDRMatch"       , "eta"              , 300   , -3    , 3     , ""  ),
  ("LooseMuonsFromALPDRMatch"       , "phi"              , 300   , -3    , 3     , ""  ),
  ("LooseMuonsFromALPDRMatch"       , "dxy"              , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsFromALPDRMatch"       , "dxyPVTraj"        , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsFromALPDRMatch"       , "dxyPVTrajErr"     , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsFromALPDRMatch"       , "dxyPVTrajSig"     , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsFromALPDRMatch"       , "dz"               , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsFromALPDRMatch"       , "dzPV"             , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsFromALPDRMatch"       , "dzPVErr"          , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsFromALPDRMatch"       , "dzPVSig"          , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsFromALPDRMatch"       , "ip3DPVSigned"     , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsFromALPDRMatch"       , "ip3DPVSignedErr"  , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsFromALPDRMatch"       , "ip3DPVSignedSig"  , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsFromALPDRMatch"       , "nSegments"         , 50     , 0    , 50   , ""  ),
  ("LooseMuonsFromALPDRMatch"       , "invMass"          , 10000 , 0     , 100   , ""  ),
  ("LooseMuonsFromALPDRMatch"       , "deltaR"           , 1000  , 0     , 10    , ""  ),
  ("LooseMuonsFromALPDRMatch"       , "outerDeltaR"      , 1000  , 0     , 10    , ""  ),
  ("LooseMuonsFromALPDRMatch"       , "deltaEta"         , 1000  , 0     , 10    , ""  ),
  ("LooseMuonsFromALPDRMatch"       , "deltaPhi"         , 1000  , 0     , 10    , ""  ),

  ("Event"          , "nLooseMuonsFromALPOuterDRMatch"       , 50    , 0     , 50    , ""  ),
  ("Event"          , "nLooseMuonsFromALPOuterDRMatch_DSA"   , 50    , 0     , 50    , ""  ),
  ("Event"          , "nLooseMuonsFromALPOuterDRMatch_PAT"   , 50    , 0     , 50    , ""  ),
  ("LooseMuonsFromALPOuterDRMatch"  , "pt"               , 2000  , 0     , 1000  , ""  ),
  ("LooseMuonsFromALPOuterDRMatch"  , "eta"              , 300   , -3    , 3     , ""  ),
  ("LooseMuonsFromALPOuterDRMatch"  , "phi"              , 300   , -3    , 3     , ""  ),
  ("LooseMuonsFromALPOuterDRMatch"  , "dxy"              , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatch"  , "dxyPVTraj"        , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatch"  , "dxyPVTrajErr"     , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatch"  , "dxyPVTrajSig"     , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatch"  , "dz"               , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatch"  , "dzPV"             , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatch"  , "dzPVErr"          , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatch"  , "dzPVSig"          , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatch"  , "ip3DPVSigned"     , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatch"  , "ip3DPVSignedErr"  , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatch"  , "ip3DPVSignedSig"  , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatch"  , "nSegments"         , 50     , 0    , 50   , ""  ),
  ("LooseMuonsFromALPOuterDRMatch"  , "invMass"          , 10000 , 0     , 100   , ""  ),
  ("LooseMuonsFromALPOuterDRMatch"  , "deltaR"           , 1000  , 0     , 10    , ""  ),
  ("LooseMuonsFromALPOuterDRMatch"  , "outerDeltaR"      , 1000  , 0     , 10    , ""  ),
  ("LooseMuonsFromALPOuterDRMatch"  , "deltaEta"         , 1000  , 0     , 10    , ""  ),
  ("LooseMuonsFromALPOuterDRMatch"  , "deltaPhi"         , 1000  , 0     , 10    , ""  ),
  ("LooseMuonsFromALPOuterDRMatch"  , "minDeltaR"        , 1000  , 0     , 10    , ""  ),
  ("LooseMuonsFromALPOuterDRMatch"  , "minOuterDeltaR"   , 1000  , 0     , 10    , ""  ),
  ("LooseMuonsFromALPOuterDRMatch"  , "minProxDeltaR"    , 1000  , 0     , 10    , ""  ),

  ("Event"          , "nLooseMuonsFromALPSegmentMatch"       , 50    , 0     , 50    , ""  ),
  ("Event"          , "nLooseMuonsFromALPSegmentMatch_DSA"   , 50    , 0     , 50    , ""  ),
  ("Event"          , "nLooseMuonsFromALPSegmentMatch_PAT"   , 50    , 0     , 50    , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "pt"               , 2000  , 0     , 1000  , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "eta"              , 300   , -3    , 3     , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "phi"              , 300   , -3    , 3     , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "dxy"              , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "dxyPVTraj"        , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "dxyPVTrajErr"     , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "dxyPVTrajSig"     , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "dz"               , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "dzPV"             , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "dzPVErr"          , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "dzPVSig"          , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "ip3DPVSigned"     , 20000  , -2000    , 2000   , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "ip3DPVSignedErr"  , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "ip3DPVSignedSig"  , 10000  , 0    , 2000   , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "nSegments"         , 50     , 0    , 50   , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "invMass"          , 10000 , 0     , 100   , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "deltaR"           , 1000  , 0     , 10    , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "outerDeltaR"      , 1000  , 0     , 10    , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "deltaEta"         , 1000  , 0     , 10    , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "deltaPhi"         , 1000  , 0     , 10    , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "minDeltaR"        , 1000  , 0     , 10    , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "minOuterDeltaR"   , 1000  , 0     , 10    , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "minProxDeltaR"    , 1000  , 0     , 10    , ""  ),

  ("Event"          , "nLooseMuonsFromALPDRMatchVertex"           , 50     , 0      , 50     , ""  ),
  ("LooseMuonsFromALPDRMatchVertex" , "chi2"                      , 500    , 0      , 500    , ""  ),
  ("LooseMuonsFromALPDRMatchVertex" , "vxy"                       , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPDRMatchVertex" , "vxySigma"                  , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPDRMatchVertex" , "vx"                        , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPDRMatchVertex" , "vy"                        , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPDRMatchVertex" , "vxyz"                      , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPDRMatchVertex" , "vz"                        , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPDRMatchVertex" , "dR"                        , 500    , 0      , 10     , ""  ),
  ("LooseMuonsFromALPDRMatchVertex" , "proxDR"                    , 500    , 0      , 10     , ""  ),
  ("LooseMuonsFromALPDRMatchVertex" , "idx1"                      , 100    , 0      , 100    , ""  ),
  ("LooseMuonsFromALPDRMatchVertex" , "idx2"                      , 100    , 0      , 100    , ""  ),
  ("LooseMuonsFromALPDRMatchVertex" , "isDSAMuon1"                , 10     , 0      , 10     , ""  ),
  ("LooseMuonsFromALPDRMatchVertex" , "isDSAMuon2"                , 10     , 0      , 10     , ""  ),
  ("LooseMuonsFromALPDRMatchVertex" , "displacedTrackIso03Dimuon1"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPDRMatchVertex" , "displacedTrackIso04Dimuon1"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPDRMatchVertex" , "displacedTrackIso03Dimuon2"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPDRMatchVertex" , "displacedTrackIso04Dimuon2"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPDRMatchVertex" , "displacedTrackIso03Muon1"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPDRMatchVertex" , "displacedTrackIso04Muon1"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPDRMatchVertex" , "displacedTrackIso03Muon2"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPDRMatchVertex" , "displacedTrackIso04Muon2"     , 5000  , 0     , 500    , ""  ),
  ("Event"          , "nLooseMuonsFromALPDRMatchVertex_PatDSA"     , 50     , 0      , 50     , ""  ),
  ("LooseMuonsFromALPDRMatchVertex_PatDSA"     , "chi2"         , 500    , 0      , 500    , ""  ),
  ("LooseMuonsFromALPDRMatchVertex_PatDSA"     , "vxy"          , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPDRMatchVertex_PatDSA"     , "vxySigma"     , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPDRMatchVertex_PatDSA"     , "vx"           , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPDRMatchVertex_PatDSA"     , "vy"           , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPDRMatchVertex_PatDSA"     , "vz"           , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPDRMatchVertex_PatDSA"     , "vxyz"         , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPDRMatchVertex_PatDSA"     , "dR"           , 500    , 0      , 10     , ""  ),
  ("LooseMuonsFromALPDRMatchVertex_PatDSA"     , "proxDR"       , 500    , 0      , 10     , ""  ),
  ("Event"          , "nLooseMuonsFromALPDRMatchVertex_Pat"        , 50     , 0      , 50     , ""  ),
  ("LooseMuonsFromALPDRMatchVertex_Pat"  , "chi2"            , 500    , 0      , 500    , ""  ),
  ("LooseMuonsFromALPDRMatchVertex_Pat"  , "vxy"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPDRMatchVertex_Pat"  , "vxySigma"        , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPDRMatchVertex_Pat"  , "vx"              , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPDRMatchVertex_Pat"  , "vy"              , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPDRMatchVertex_Pat"  , "vz"              , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPDRMatchVertex_Pat"  , "vxyz"            , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPDRMatchVertex_Pat"  , "dR"              , 500    , 0      , 10     , ""  ),
  ("LooseMuonsFromALPDRMatchVertex_Pat"  , "proxDR"          , 500    , 0      , 10     , ""  ),
  ("Event"          , "nLooseMuonsFromALPDRMatchVertex_DSA"        , 50     , 0      , 50     , ""  ),
  ("LooseMuonsFromALPDRMatchVertex_DSA"  , "chi2"            , 500    , 0      , 500    , ""  ),
  ("LooseMuonsFromALPDRMatchVertex_DSA"  , "vxy"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPDRMatchVertex_DSA"  , "vxySigma"        , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPDRMatchVertex_DSA"  , "vx"              , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPDRMatchVertex_DSA"  , "vy"              , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPDRMatchVertex_DSA"  , "vz"              , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPDRMatchVertex_DSA"  , "vxyz"            , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPDRMatchVertex_DSA"  , "dR"              , 500    , 0      , 10     , ""  ),
  ("LooseMuonsFromALPDRMatchVertex_DSA"  , "proxDR"          , 500    , 0      , 10     , ""  ),

  ("Event"          , "nLooseMuonsFromALPOuterDRMatchVertex"       , 50     , 0      , 50     , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex" , "chi2"                  , 500    , 0      , 500    , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex" , "vxy"                   , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex" , "vxySigma"              , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex" , "vx"                    , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex" , "vy"                    , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex" , "vz"                    , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex" , "vxyz"                  , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex" , "dR"                    , 500    , 0      , 10     , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex" , "proxDR"                , 500    , 0      , 10     , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex" , "idx1"                  , 100    , 0      , 100    , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex" , "idx2"                  , 100    , 0      , 100    , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex" , "isDSAMuon1"            , 10     , 0      , 10     , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex" , "isDSAMuon2"            , 10     , 0      , 10     , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex" , "displacedTrackIso03Dimuon1"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex" , "displacedTrackIso04Dimuon1"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex" , "displacedTrackIso03Dimuon2"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex" , "displacedTrackIso04Dimuon2"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex" , "displacedTrackIso03Muon1"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex" , "displacedTrackIso04Muon1"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex" , "displacedTrackIso03Muon2"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex" , "displacedTrackIso04Muon2"     , 5000  , 0     , 500    , ""  ),
  ("Event"          , "nLooseMuonsFromALPOuterDRMatchVertex_PatDSA", 50     , 0      , 50     , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex_PatDSA"    , "chi2"        , 500    , 0      , 500    , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex_PatDSA"    , "vxy"         , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex_PatDSA"    , "vxySigma"    , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex_PatDSA"    , "vx"          , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex_PatDSA"    , "vy"          , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex_PatDSA"    , "vz"          , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex_PatDSA"    , "vxyz"        , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex_PatDSA"    , "dR"          , 500    , 0      , 10     , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex_PatDSA"    , "proxDR"      , 500    , 0      , 10     , ""  ),
  ("Event"          , "nLooseMuonsFromALPOuterDRMatchVertex_Pat"   , 50     , 0      , 50     , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex_Pat"    , "chi2"           , 500    , 0      , 500    , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex_Pat"    , "vxy"            , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex_Pat"    , "vxySigma"       , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex_Pat"    , "vx"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex_Pat"    , "vy"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex_Pat"    , "vz"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex_Pat"    , "vxyz"           , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex_Pat"    , "dR"             , 500    , 0      , 10     , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex_Pat"    , "proxDR"         , 500    , 0      , 10     , ""  ),
  ("Event"          , "nLooseMuonsFromALPOuterDRMatchVertex_DSA"   , 50     , 0      , 50     , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex_DSA"    , "chi2"           , 500    , 0      , 500    , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex_DSA"    , "vxy"            , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex_DSA"    , "vxySigma"       , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex_DSA"    , "vx"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex_DSA"    , "vy"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex_DSA"    , "vz"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex_DSA"    , "vxyz"           , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex_DSA"    , "dR"             , 500    , 0      , 10     , ""  ),
  ("LooseMuonsFromALPOuterDRMatchVertex_DSA"    , "proxDR"         , 500    , 0      , 10     , ""  ),

  ("Event"          , "nLooseMuonsFromALPSegmentMatchVertex"       , 50     , 0      , 50    , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex" , "chi2"                  , 500    , 0      , 500   , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex" , "vxy"                   , 10000  , -1000  , 1000  , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex" , "vxySigma"              , 10000  , -1000  , 1000  , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex" , "vx"                    , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex" , "vy"                    , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex" , "vz"                    , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex" , "vxyz"                  , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex" , "dR"                    , 500    , 0      , 10     , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex" , "proxDR"                , 500    , 0      , 10     , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex" , "idx1"                  , 100    , 0      , 100    , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex" , "idx2"                  , 100    , 0      , 100    , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex" , "isDSAMuon1"            , 10     , 0      , 10     , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex" , "isDSAMuon2"            , 10     , 0      , 10     , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex" , "displacedTrackIso03Dimuon1"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex" , "displacedTrackIso04Dimuon1"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex" , "displacedTrackIso03Dimuon2"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex" , "displacedTrackIso04Dimuon2"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex" , "displacedTrackIso03Muon1"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex" , "displacedTrackIso04Muon1"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex" , "displacedTrackIso03Muon2"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex" , "displacedTrackIso04Muon2"     , 5000  , 0     , 500    , ""  ),
  ("Event"          , "nLooseMuonsFromALPSegmentMatchVertex_PatDSA", 50    , 0     , 50    , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex_PatDSA"    , "chi2"        , 500   , 0     , 500   , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex_PatDSA"    , "vxy"         , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex_PatDSA"    , "vxySigma"    , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex_PatDSA"    , "vx"          , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex_PatDSA"    , "vy"          , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex_PatDSA"    , "vz"          , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex_PatDSA"    , "vxyz"        , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex_PatDSA"    , "dR"          , 500   , 0     , 10    , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex_PatDSA"    , "proxDR"      , 500   , 0     , 10    , ""  ),
  ("Event"          , "nLooseMuonsFromALPSegmentMatchVertex_Pat"   , 50    , 0     , 50    , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex_Pat"    , "chi2"           , 500   , 0     , 500   , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex_Pat"    , "vxy"            , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex_Pat"    , "vxySigma"       , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex_Pat"    , "vx"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex_Pat"    , "vy"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex_Pat"    , "vz"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex_Pat"    , "vxyz"           , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex_Pat"    , "dR"             , 500   , 0     , 10    , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex_Pat"    , "proxDR"         , 500   , 0     , 10    , ""  ),
  ("Event"          , "nLooseMuonsFromALPSegmentMatchVertex_DSA"   , 50    , 0     , 50    , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex_DSA"    , "chi2"           , 500   , 0     , 500   , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex_DSA"    , "vxy"            , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex_DSA"    , "vxySigma"       , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex_DSA"    , "vx"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex_DSA"    , "vy"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex_DSA"    , "vz"             , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex_DSA"    , "vxyz"           , 10000  , -1000  , 1000   , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex_DSA"    , "dR"             , 500   , 0     , 10    , ""  ),
  ("LooseMuonsFromALPSegmentMatchVertex_DSA"    , "proxDR"         , 500   , 0     , 10    , ""  ),
  )

if runLLPNanoAODHistograms:
  histParams = histParams + LLPNanoAOD_histParams
if runMuonMatchingHistograms:
  histParams = histParams + MuonMatching_histParams
if runGenMuonHistograms:
  histParams = histParams + GenMuon_histParams

histParams2D = (

)

LLPNanoAOD_histParams2D = (

)

MuonMatching_histParams2D = ( 
  ("LooseDSAMuons_muonMatch1_nSegments",               50  , 0    , 50, 50  , 0    , 50   , ""  ),
  ("LooseDSAMuons_muonMatch2_nSegments",               50  , 0    , 50, 50  , 0    , 50   , ""  ),
  ("LooseDSAMuons_muonMatch3_nSegments",               50  , 0    , 50, 50  , 0    , 50   , ""  ),

  ("SegmentMatchLooseMuons_LooseDSAMuons_genMinDR",    1000 , 0    , 10  , 1000 , 0    , 10   , ""  ),
  ("SegmentMatchLooseMuons_LooseDSAMuons_genMinDRidx", 100  , 0    , 100 , 100  , 0    , 100  , ""  ),
  ("SegmentMatchLooseMuons_LooseDSAMuons_eta",         60   , -3   , 3   , 60   , -3   , 3    , ""  ),
  ("SegmentMatchLooseMuons_LooseDSAMuons_phi",         60   , -3   , 3   , 60   , -3   , 3    , ""  ),
  ("SegmentMatchLooseMuons_LooseDSAMuons_outerEta",    60   , -3   , 3   , 60   , -3   , 3    , ""  ),
  ("SegmentMatchLooseMuons_LooseDSAMuons_outerPhi",    60   , -3   , 3   , 60   , -3   , 3    , ""  ),

  ("SegmentMatchLooseMuons_eta_outerEta",              60   , -3   , 3   , 60   , -3   , 3    , ""  ),
  ("SegmentMatchLooseMuons_phi_outerPhi",              60   , -3   , 3   , 60   , -3   , 3    , ""  ),
  ("SegmentMatchLooseDSAMuons_eta_outerEta",           60   , -3   , 3   , 60   , -3   , 3    , ""  ),
  ("SegmentMatchLooseDSAMuons_phi_outerPhi",           60   , -3   , 3   , 60   , -3   , 3    , ""  ),
)

GenMuon_histParams2D = (

)

if runLLPNanoAODHistograms:
  histParams2D = histParams2D + LLPNanoAOD_histParams2D
if runMuonMatchingHistograms:
  histParams2D = histParams2D + MuonMatching_histParams2D
if runGenMuonHistograms:
  histParams2D = histParams2D + GenMuon_histParams2D

specialBranchSizes = {}