from scale_factors_config import *
from ttalps_extra_collections import extraEventCollections

nEvents = -1
printEveryNevents = 10000

runDefaultHistograms = True
runTriggerHistograms = False
runPileupHistograms = False
runLLPNanoAODHistograms = True

weightsBranchName = "genWeight"
eventsTreeName = "Events"

pileupScaleFactorsPath = "/nfs/dust/cms/user/jniedzie/ttalps_cms/pileup_scale_factors.root"
pileupScaleFactorsHistName = "pileup_scale_factors"

applyScaleFactors = {
  "muon": True,
  "muonTrigger": True,
  "pileup": True,
  "bTagging": True,
}

defaultHistParams = (
#  collection             variable               bins    xmin    xmax    dir
  ("Event"              , "PV_npvs"             , 300   , 0     , 300   , ""  ),
  ("Event"              , "PV_npvsGood"         , 300   , 0     , 300   , ""  ),
  ("Event"              , "MET_pt"              , 1000  , 0     , 1000  , ""  ),
  
  ("Event"              , "nMuon"               , 50    , 0     , 50    , ""  ),
  ("Muon"               , "pt"                  , 2000  , 0     , 1000  , ""  ),
  ("Muon"               , "eta"                 , 300   , -3    , 3     , ""  ),
  ("Muon"               , "dxy"                 , 8000  , -1000  , 1000   , ""  ),
  ("Muon"               , "dz"                  , 8000  , -1000  , 1000   , ""  ),
  
  ("Event"              , "nTightMuons"         , 50    , 0     , 50    , ""  ),
  ("TightMuons"         , "pt"                  , 2000  , 0     , 1000  , ""  ),
  ("TightMuons"         , "eta"                 , 300   , -3    , 3     , ""  ),
  ("TightMuons"         , "dxy"                 , 8000  , -1000  , 1000   , ""  ),
  ("TightMuons"         , "dz"                  , 8000  , -1000  , 1000   , ""  ),
  ("TightMuons"         , "pfRelIso04_all"      , 2000  , -10   , 10    , ""  ),
  ("TightMuons"         , "pfRelIso03_chg"      , 2000  , -10   , 10    , ""  ),
  ("TightMuons"         , "pfRelIso03_all"      , 2000  , -10   , 10    , ""  ),
  ("TightMuons"         , "tkRelIso"            , 2000  , -10   , 10    , ""  ),
  ("TightMuons"         , "miniPFRelIso_chg"    , 2000  , -10   , 10    , ""  ),
  ("TightMuons"         , "miniPFRelIso_all"    , 2000  , -10   , 10    , ""  ),
  ("TightMuons"         , "jetRelIso"           , 2000  , -10   , 10    , ""  ),

  
  ("Event"              , "nLooseMuons"         , 50    , 0     , 50    , ""  ),
  ("LooseMuons"         , "pt"                  , 2000  , 0     , 1000  , ""  ),
  ("LooseMuons"         , "eta"                 , 300   , -3    , 3     , ""  ),
  ("LooseMuons"         , "dxy"                 , 8000  , -1000  , 1000   , ""  ),
  ("LooseMuons"         , "dz"                  , 8000  , -1000  , 1000   , ""  ),
  ("LooseMuons"         , "pfRelIso04_all"      , 2000  , -10   , 10    , ""  ),
  ("LooseMuons"         , "pfRelIso03_chg"      , 2000  , -10   , 10    , ""  ),
  ("LooseMuons"         , "pfRelIso03_all"      , 2000  , -10   , 10    , ""  ),
  ("LooseMuons"         , "tkRelIso"            , 2000  , -10   , 10    , ""  ),
  ("LooseMuons"         , "miniPFRelIso_chg"    , 2000  , -10   , 10    , ""  ),
  ("LooseMuons"         , "miniPFRelIso_all"    , 2000  , -10   , 10    , ""  ),
  ("LooseMuons"         , "jetRelIso"           , 2000  , -10   , 10    , ""  ),
  
  ("Event"              , "nElectron"           , 50    , 0     , 50    , ""  ),
  ("Electron"           , "pt"                  , 2000  , 0     , 1000  , ""  ),
  ("Electron"           , "eta"                 , 300   , -3    , 3     , ""  ),
  ("Electron"           , "dxy"                 , 8000  , -1000  , 1000   , ""  ),
  ("Electron"           , "dz"                  , 8000  , -1000  , 1000   , ""  ),
  
  ("Event"              , "nLooseElectrons"     , 50    , 0     , 50    , ""  ),
  ("LooseElectrons"     , "pt"                  , 2000  , 0     , 1000  , ""  ),
  ("LooseElectrons"     , "eta"                 , 300   , -3    , 3     , ""  ),
  ("LooseElectrons"     , "dxy"                 , 8000  , -1000  , 1000   , ""  ),
  ("LooseElectrons"     , "dz"                  , 8000  , -1000  , 1000   , ""  ),
  
  ("Event"              , "nJet"                , 50    , 0     , 50    , ""  ),
  ("Jet"                , "pt"                  , 2000  , 0     , 1000  , ""  ),
  ("Jet"                , "eta"                 , 300   , -3    , 3     , ""  ),
  ("Jet"                , "phi"                 , 300   , -3    , 3     , ""  ),
  ("Jet"                , "btagDeepB"           , 200   , -1    , 1     , ""  ),
  
  ("Event"              , "nGoodJets"           , 50    , 0     , 50    , ""  ),
  ("GoodJets"           , "pt"                  , 2000  , 0     , 2000  , ""  ),
  ("GoodJets"           , "eta"                 , 300   , -3    , 3     , ""  ),
  ("GoodJets"           , "phi"                 , 300   , -3    , 3     , ""  ),
  ("GoodJets"           , "btagDeepB"           , 200   , -1    , 1     , ""  ),
  ("GoodJets"           , "btagDeepFlavB"       , 200   , -1    , 1     , ""  ),
  
  ("Event"                    , "nGoodMediumBtaggedJets"    , 50    , 0     , 50    , ""  ),
  ("GoodMediumBtaggedJets"    , "pt"                  , 2000  , 0     , 2000  , ""  ),
  ("GoodMediumBtaggedJets"    , "eta"                 , 300   , -3    , 3     , ""  ),
  ("GoodMediumBtaggedJets"    , "phi"                 , 300   , -3    , 3     , ""  ),
  ("GoodMediumBtaggedJets"    , "btagDeepB"           , 200   , -1    , 1     , ""  ),
  ("GoodMediumBtaggedJets"    , "btagDeepFlavB"       , 200   , -1    , 1     , ""  ),
  
  ("Event"                    , "nGoodNonTightBtaggedJets" , 50    , 0     , 50    , ""  ),
  ("GoodNonTightBtaggedJets"  , "pt"                  , 2000  , 0     , 2000  , ""  ),
  ("GoodNonTightBtaggedJets"  , "eta"                 , 300   , -3    , 3     , ""  ),
  ("GoodNonTightBtaggedJets"  , "phi"                 , 300   , -3    , 3     , ""  ),
  ("GoodNonTightBtaggedJets"  , "btagDeepB"           , 200   , -1    , 1     , ""  ),
  ("GoodNonTightBtaggedJets"  , "btagDeepFlavB"       , 200   , -1    , 1     , ""  ),

)

LLPNanoAOD_defaultHistParams = (

  ("Muon"               , "idx"                 , 50    , 0     , 50    , ""  ),
  ("Muon"               , "dsaMatch1"           , 100   , 0     , 100   , ""  ),
  ("Muon"               , "dsaMatch1idx"        , 100   , 0     , 100   , ""  ),
  ("Muon"               , "dsaMatch2"           , 100   , 0     , 100   , ""  ),
  ("Muon"               , "dsaMatch2idx"        , 100   , 0     , 100   , ""  ),
  ("Muon"               , "dsaMatch3"           , 100   , 0     , 100   , ""  ),
  ("Muon"               , "dsaMatch3idx"        , 100   , 0     , 100   , ""  ),
  ("Muon"               , "dsaMatch4"           , 100   , 0     , 100   , ""  ),
  ("Muon"               , "dsaMatch4idx"        , 100   , 0     , 100   , ""  ),
  ("Muon"               , "dsaMatch5"           , 100   , 0     , 100   , ""  ),
  ("Muon"               , "dsaMatch5idx"        , 100   , 0     , 100   , ""  ),
  ("Muon"               , "outerEta"            , 300   , -3    , 3     , ""  ),
  ("Muon"               , "outerPhi"            , 300   , -3    , 3     , ""  ),

  ("LooseMuons"               , "idx"                 , 50    , 0     , 50    , ""  ),
  ("LooseMuons"               , "dzPV"                , 8000  , -1000 , 1000  , ""  ),
  ("LooseMuons"               , "dxyPVTraj"           , 8000  , -1000 , 1000  , ""  ),
  ("LooseMuons"               , "dxyPVSigned"         , 8000  , -1000 , 1000  , ""  ),
  ("LooseMuons"               , "ip3DPVSigned"        , 8000  , -1000 , 1000  , ""  ),
  # ("LooseMuons"               , "dxyBS"               , 8000  , -1000 , 1000  , ""  ),
  ("LooseMuons"               , "dzBS"                , 8000  , -1000 , 1000  , ""  ),
  ("LooseMuons"               , "dxyBSTraj"           , 8000  , -1000 , 1000  , ""  ),
  ("LooseMuons"               , "dxyBSSigned"         , 8000  , -1000 , 1000  , ""  ),
  ("LooseMuons"               , "ip3DBSSigned"        , 8000  , -1000 , 1000  , ""  ),
  ("LooseMuons"               , "dsaMatch1"           , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "dsaMatch1idx"        , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "dsaMatch2"           , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "dsaMatch2idx"        , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "dsaMatch3"           , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "dsaMatch3idx"        , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "dsaMatch4"           , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "dsaMatch4idx"        , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "dsaMatch5"           , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "dsaMatch5idx"        , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "outerEta"            , 300   , -3    , 3     , ""  ),
  ("LooseMuons"               , "outerPhi"            , 300   , -3    , 3     , ""  ),
  ("LooseMuons"               , "trkNumPlanes"        , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "trkNumHits"          , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "trkNumDTHits"        , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "trkNumCSCHits"       , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "trkNumPixelHits"     , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "trkNumTrkLayers"     , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "normChi2"            , 100   , 0     , 100   , ""  ),
  ("LooseMuons"               , "trkPt"               , 2000  , 0     , 1000  , ""  ),
  ("LooseMuons"               , "trkPtErr"            , 2000  , 0     , 1000  , ""  ),

  ("Event"              , "nDSAMuon"            , 50    , 0     , 50    , ""  ),
  ("DSAMuon"            , "idx"                 , 50    , 0     , 50    , ""  ),
  ("DSAMuon"            , "pt"                  , 2000  , 0     , 1000  , ""  ),
  ("DSAMuon"            , "eta"                 , 300   , -3    , 3     , ""  ),
  ("DSAMuon"            , "dxy"                 , 8000  , -1000 , 1000  , ""  ),
  ("DSAMuon"            , "dz"                  , 8000  , -1000 , 1000  , ""  ),
  ("DSAMuon"            , "muonMatch1"          , 100   , 0     , 100   , ""  ),
  ("DSAMuon"            , "muonMatch1idx"       , 100   , 0     , 100   , ""  ),
  ("DSAMuon"            , "muonMatch2"          , 100   , 0     , 100   , ""  ),
  ("DSAMuon"            , "muonMatch2idx"       , 100   , 0     , 100   , ""  ),
  ("DSAMuon"            , "muonMatch3"          , 100   , 0     , 100   , ""  ),
  ("DSAMuon"            , "muonMatch3idx"       , 100   , 0     , 100   , ""  ),
  ("DSAMuon"            , "muonMatch4"          , 100   , 0     , 100   , ""  ),
  ("DSAMuon"            , "muonMatch4idx"       , 100   , 0     , 100   , ""  ),
  ("DSAMuon"            , "muonMatch5"          , 100   , 0     , 100   , ""  ),
  ("DSAMuon"            , "muonMatch5idx"       , 100   , 0     , 100   , ""  ),
  ("DSAMuon"            , "outerEta"            , 300   , -3    , 3     , ""  ),
  ("DSAMuon"            , "outerPhi"            , 300   , -3    , 3     , ""  ),
  ("DSAMuon"            , "displacedID"         , 50    , 0     , 50    , ""  ),

  ("Event"              , "nLooseDSAMuons"            , 50    , 0     , 50    , ""  ),
  ("LooseDSAMuons"            , "idx"                 , 50    , 0     , 50    , ""  ),
  ("LooseDSAMuons"            , "pt"                  , 2000  , 0     , 1000  , ""  ),
  ("LooseDSAMuons"            , "eta"                 , 300   , -3    , 3     , ""  ),
  ("LooseDSAMuons"            , "dxy"                 , 8000  , -1000 , 1000  , ""  ),
  ("LooseDSAMuons"            , "dz"                  , 8000  , -1000 , 1000  , ""  ),
  ("LooseDSAMuons"            , "idx"                 , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "dzPV"                , 8000  , -1000 , 1000  , ""  ),
  ("LooseDSAMuons"            , "dxyPVTraj"           , 8000  , -1000 , 1000  , ""  ),
  ("LooseDSAMuons"            , "dxyPVSigned"         , 8000  , -1000 , 1000  , ""  ),
  ("LooseDSAMuons"            , "ip3DPVSigned"        , 8000  , -1000 , 1000  , ""  ),
  # ("LooseDSAMuons"            , "dxyBS"               , 8000  , -1000 , 1000  , ""  ),
  ("LooseDSAMuons"            , "dxyBSTraj"           , 8000  , -1000 , 1000  , ""  ),
  ("LooseDSAMuons"            , "dxyBSSigned"         , 8000  , -1000 , 1000  , ""  ),
  ("LooseDSAMuons"            , "ip3DBSSigned"        , 8000  , -1000 , 1000  , ""  ),
  ("LooseDSAMuons"            , "muonMatch1"          , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "muonMatch1idx"       , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "muonMatch2"          , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "muonMatch2idx"       , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "muonMatch3"          , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "muonMatch3idx"       , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "muonMatch4"          , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "muonMatch4idx"       , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "muonMatch5"          , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "muonMatch5idx"       , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "outerEta"            , 300   , -3    , 3     , ""  ),
  ("LooseDSAMuons"            , "outerPhi"            , 300   , -3    , 3     , ""  ),
  ("LooseDSAMuons"            , "trkNumPlanes"        , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "trkNumHits"          , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "trkNumDTHits"        , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "trkNumCSCHits"       , 100   , 0     , 100   , ""  ),
  ("LooseDSAMuons"            , "displacedID"         , 50    , 0     , 50    , ""  ),

  ("Event"              , "nPatMuonVertex"      , 50    , 0     , 50    , ""  ),
  ("PatMuonVertex"      , "chi2"                , 500   , 0     , 500   , ""  ),
  ("PatMuonVertex"      , "vxy"                 , 2000  , -500  , 500   , ""  ),
  ("PatMuonVertex"      , "vxySigma"            , 2000  , -500  , 500   , ""  ),
  ("PatMuonVertex"      , "vz"                  , 2000  , -500  , 500   , ""  ),
  ("PatMuonVertex"      , "dR"                  , 500   , 0     , 10    , ""  ),
  ("PatMuonVertex"      , "idx1"                , 100   , 0     , 100   , ""  ),
  ("PatMuonVertex"      , "idx2"                , 100   , 0     , 100   , ""  ),
  ("PatMuonVertex"      , "isDSAMuon1"          , 10    , 0     , 10    , ""  ),
  ("PatMuonVertex"      , "isDSAMuon2"          , 10    , 0     , 10    , ""  ),

  ("Event"              , "nPatDSAMuonVertex"   , 50    , 0     , 50    , ""  ),
  ("PatDSAMuonVertex"   , "chi2"                , 500   , 0     , 500   , ""  ),
  ("PatDSAMuonVertex"   , "vxy"                 , 2000  , -500  , 500   , ""  ),
  ("PatDSAMuonVertex"   , "vxySigma"            , 2000  , -500  , 500   , ""  ),
  ("PatDSAMuonVertex"   , "vz"                  , 2000  , -500  , 500   , ""  ),
  ("PatDSAMuonVertex"   , "dR"                  , 500   , 0     , 10    , ""  ),
  ("PatDSAMuonVertex"   , "idx1"                , 100   , 0     , 100   , ""  ),
  ("PatDSAMuonVertex"   , "idx2"                , 100   , 0     , 100   , ""  ),
  ("PatDSAMuonVertex"   , "isDSAMuon1"          , 10    , 0     , 10    , ""  ),
  ("PatDSAMuonVertex"   , "isDSAMuon2"          , 10    , 0     , 10    , ""  ),

  ("Event"              , "nDSAMuonVertex"      , 50    , 0     , 50    , ""  ),
  ("DSAMuonVertex"      , "chi2"                , 500   , 0     , 500   , ""  ),
  ("DSAMuonVertex"      , "vxy"                 , 2000  , -500  , 500   , ""  ),
  ("DSAMuonVertex"      , "vxySigma"            , 2000  , -500  , 500   , ""  ),
  ("DSAMuonVertex"      , "vz"                  , 2000  , -500  , 500   , ""  ),
  ("DSAMuonVertex"      , "dR"                  , 500   , 0     , 10    , ""  ),
  ("DSAMuonVertex"      , "idx1"                , 100   , 0     , 100   , ""  ),
  ("DSAMuonVertex"      , "idx2"                , 100   , 0     , 100   , ""  ),
  ("DSAMuonVertex"      , "isDSAMuon1"          , 10    , 0     , 10    , ""  ),
  ("DSAMuonVertex"      , "isDSAMuon2"          , 10    , 0     , 10    , ""  ),

  # ("Event"              , "nBS"                 , 50    , 0     , 50    , ""  ),
  # ("BS"                 , "chi2"                , 500   , 0     , 500   , ""  ),
  # ("BS"                 , "ndof"                , 100   , 0     , 100   , ""  ),
  # ("BS"                 , "x"                   , 500   , 0     , 500   , ""  ),
  # ("BS"                 , "y"                   , 500   , 0     , 500   , ""  ),
  # ("BS"                 , "z"                   , 500   , 0     , 500   , ""  ),
)

if runLLPNanoAODHistograms:
  defaultHistParams = defaultHistParams + LLPNanoAOD_defaultHistParams

histParams = (
#  collection         variable                      bins   xmin   xmax    dir
  ("Muon"           , "leadingPt"                 , 2000  , 0   , 1000  , ""  ),
  ("TightMuons"     , "leadingPt"                 , 2000  , 0   , 1000  , ""  ),
  ("LooseMuons"     , "leadingPt"                 , 2000  , 0   , 1000  , ""  ),
  ("Electron"       , "leadingPt"                 , 2000  , 0   , 1000  , ""  ),
  ("LooseElectrons" , "leadingPt"                 , 2000  , 0   , 1000  , ""  ),
  ("Jet"            , "leadingPt"                 , 2000  , 0   , 1000  , ""  ),
  ("GoodJets"       , "leadingPt"                 , 2000  , 0   , 1000  , ""  ),
  
  ("Muon"           , "subleadingPt"              , 2000  , 0   , 1000  , ""  ),
  ("TightMuons"     , "subleadingPt"              , 2000  , 0   , 1000  , ""  ),
  ("LooseMuons"     , "subleadingPt"              , 2000  , 0   , 1000  , ""  ),
  ("Electron"       , "subleadingPt"              , 2000  , 0   , 1000  , ""  ),
  ("LooseElectrons" , "subleadingPt"              , 2000  , 0   , 1000  , ""  ),
  ("Jet"            , "subleadingPt"              , 2000  , 0   , 1000  , ""  ),
  ("GoodJets"       , "subleadingPt"              , 2000  , 0   , 1000  , ""  ),
  
  ("LooseMuons"     , "dimuonMinv"                , 200   , 0   , 200   , ""  ),
  ("LooseMuons"     , "dimuonMinvClosestToZ"      , 200   , 0   , 200   , ""  ),
  ("LooseMuons"     , "dimuonDeltaRclosestToZ"    , 200   , -10 , 10    , ""  ),
  ("LooseMuons"     , "dimuonDeltaEtaclosestToZ"  , 200   , -10 , 10    , ""  ),
  ("LooseMuons"     , "dimuonDeltaPhiclosestToZ"  , 200   , -10 , 10    , ""  ),
  ("GoodJets"       , "minvBjet2jets"             , 2000  , 0   , 2000  , ""  ),
  ("TightMuons"     , "deltaPhiMuonMET"           , 200   , -4  , 4     , ""  ),
  ("TightMuons"     , "minvMuonMET"               , 1000  , 0   , 1000  , ""  ),
  
  ("Event"          , "normCheck"                 , 1     , 0   , 1     , ""  ),
)

LLPNanoAOD_histParams = (
  ("Event"          , "nLooseMuonsDRMatch"        , 50    , 0     , 50    , ""  ),
  ("LooseMuonsDRMatch"  , "pt"                    , 2000  , 0     , 1000  , ""  ),
  ("LooseMuonsDRMatch"  , "eta"                   , 300   , -3    , 3     , ""  ),
  ("LooseMuonsDRMatch"  , "dxy"                   , 1600  , -400  , 400   , ""  ),
  ("LooseMuonsDRMatch"  , "dz"                    , 1600  , -400  , 400   , ""  ),
  ("LooseMuonsDRMatch"  , "hasOuterDRMatch"       , 10    , 0     , 10    , ""  ),
  ("LooseMuonsDRMatch"  , "hasSegmentMatch"       , 10    , 0     , 10    , ""  ),
  ("LooseMuonsDRMatch"  , "genMuonDR"             , 1000  , 0     , 100   , ""  ),
  ("Event"          , "nLooseMuonsOuterDRMatch"   , 50    , 0     , 50    , ""  ),
  ("LooseMuonsOuterDRMatch"  , "pt"               , 2000  , 0     , 1000  , ""  ),
  ("LooseMuonsOuterDRMatch"  , "eta"              , 300   , -3    , 3     , ""  ),
  ("LooseMuonsOuterDRMatch"  , "dxy"              , 1600  , -400  , 400   , ""  ),
  ("LooseMuonsOuterDRMatch"  , "dz"               , 1600  , -400  , 400   , ""  ),
  ("LooseMuonsOuterDRMatch"  , "hasDRMatch"       , 10    , 0     , 10    , ""  ),
  ("LooseMuonsOuterDRMatch"  , "hasSegmentMatch"  , 10    , 0     , 10    , ""  ),
  ("LooseMuonsOuterDRMatch"  , "genMuonDR"        , 1000  , 0     , 100   , ""  ),
  ("Event"          , "nLooseMuonsSegmentMatch"   , 50    , 0     , 50    , ""  ),
  ("LooseMuonsSegmentMatch"  , "pt"               , 2000  , 0     , 1000  , ""  ),
  ("LooseMuonsSegmentMatch"  , "eta"              , 300   , -3    , 3     , ""  ),
  ("LooseMuonsSegmentMatch"  , "dxy"              , 1600  , -400  , 400   , ""  ),
  ("LooseMuonsSegmentMatch"  , "dz"               , 1600  , -400  , 400   , ""  ),
  ("LooseMuonsSegmentMatch"  , "hasDRMatch"       , 10    , 0     , 10    , ""  ),
  ("LooseMuonsSegmentMatch"  , "hasOuterDRMatch"  , 10    , 0     , 10    , ""  ),
  ("LooseMuonsSegmentMatch"  , "genMuonDR"        , 1000  , 0     , 100   , ""  ),

  ("Event"     , "nLooseMuonVertexDRMatch"          , 50    , 0     , 50    , ""  ),
  ("LooseMuonVertexDRMatch"      , "chi2"           , 500   , 0     , 500   , ""  ),
  ("LooseMuonVertexDRMatch"      , "vxy"            , 2000  , -500  , 500   , ""  ),
  ("LooseMuonVertexDRMatch"      , "vxySigma"       , 2000  , -500  , 500   , ""  ),
  ("LooseMuonVertexDRMatch"      , "vz"             , 2000  , -500  , 500   , ""  ),
  ("LooseMuonVertexDRMatch"      , "dR"             , 500   , 0     , 10    , ""  ),
  ("LooseMuonVertexDRMatch"      , "idx1"           , 100   , 0     , 100   , ""  ),
  ("LooseMuonVertexDRMatch"      , "idx2"           , 100   , 0     , 100   , ""  ),
  ("LooseMuonVertexDRMatch"      , "isDSAMuon1"     , 10    , 0     , 10    , ""  ),
  ("LooseMuonVertexDRMatch"      , "isDSAMuon2"     , 10    , 0     , 10    , ""  ),
  ("LooseMuonVertexDRMatch"      , "displacedTrackIso03Dimuon1"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonVertexDRMatch"      , "displacedTrackIso04Dimuon1"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonVertexDRMatch"      , "displacedTrackIso03Dimuon2"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonVertexDRMatch"      , "displacedTrackIso04Dimuon2"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonVertexDRMatch"      , "displacedTrackIso03Muon1"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonVertexDRMatch"      , "displacedTrackIso04Muon1"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonVertexDRMatch"      , "displacedTrackIso03Muon2"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonVertexDRMatch"      , "displacedTrackIso04Muon2"     , 5000  , 0     , 500    , ""  ),
  ("Event"     , "nLooseMuonVertexOuterDRMatch"     , 50    , 0     , 50    , ""  ),
  ("LooseMuonVertexOuterDRMatch" , "chi2"           , 500   , 0     , 500   , ""  ),
  ("LooseMuonVertexOuterDRMatch" , "vxy"            , 2000  , -500  , 500   , ""  ),
  ("LooseMuonVertexOuterDRMatch" , "vxySigma"       , 2000  , -500  , 500   , ""  ),
  ("LooseMuonVertexOuterDRMatch" , "vz"             , 2000  , -500  , 500   , ""  ),
  ("LooseMuonVertexOuterDRMatch" , "dR"             , 500   , 0     , 10    , ""  ),
  ("LooseMuonVertexOuterDRMatch" , "idx1"           , 100   , 0     , 100   , ""  ),
  ("LooseMuonVertexOuterDRMatch" , "idx2"           , 100   , 0     , 100   , ""  ),
  ("LooseMuonVertexOuterDRMatch" , "isDSAMuon1"     , 10    , 0     , 10    , ""  ),
  ("LooseMuonVertexOuterDRMatch" , "isDSAMuon2"     , 10    , 0     , 10    , ""  ),
  ("LooseMuonVertexOuterDRMatch" , "displacedTrackIso03Dimuon1"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonVertexOuterDRMatch" , "displacedTrackIso04Dimuon1"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonVertexOuterDRMatch" , "displacedTrackIso03Dimuon2"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonVertexOuterDRMatch" , "displacedTrackIso04Dimuon2"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonVertexOuterDRMatch" , "displacedTrackIso03Muon1"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonVertexOuterDRMatch" , "displacedTrackIso04Muon1"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonVertexOuterDRMatch" , "displacedTrackIso03Muon2"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonVertexOuterDRMatch" , "displacedTrackIso04Muon2"     , 5000  , 0     , 500    , ""  ),
  ("Event"          , "nLooseMuonVertexSegmentMatch"     , 50    , 0     , 50    , ""  ),
  ("LooseMuonVertexSegmentMatch" , "chi2"           , 500   , 0     , 500   , ""  ),
  ("LooseMuonVertexSegmentMatch" , "vxy"            , 2000  , -500  , 500   , ""  ),
  ("LooseMuonVertexSegmentMatch" , "vxySigma"       , 2000  , -500  , 500   , ""  ),
  ("LooseMuonVertexSegmentMatch" , "vz"             , 2000  , -500  , 500   , ""  ),
  ("LooseMuonVertexSegmentMatch" , "dR"             , 500   , 0     , 10    , ""  ),
  ("LooseMuonVertexSegmentMatch" , "idx1"           , 100   , 0     , 100   , ""  ),
  ("LooseMuonVertexSegmentMatch" , "idx2"           , 100   , 0     , 100   , ""  ),
  ("LooseMuonVertexSegmentMatch" , "isDSAMuon1"     , 10    , 0     , 10    , ""  ),
  ("LooseMuonVertexSegmentMatch" , "isDSAMuon2"     , 10    , 0     , 10    , ""  ),
  ("LooseMuonVertexSegmentMatch" , "displacedTrackIso03Dimuon1"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonVertexSegmentMatch" , "displacedTrackIso04Dimuon1"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonVertexSegmentMatch" , "displacedTrackIso03Dimuon2"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonVertexSegmentMatch" , "displacedTrackIso04Dimuon2"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonVertexSegmentMatch" , "displacedTrackIso03Muon1"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonVertexSegmentMatch" , "displacedTrackIso04Muon1"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonVertexSegmentMatch" , "displacedTrackIso03Muon2"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonVertexSegmentMatch" , "displacedTrackIso04Muon2"     , 5000  , 0     , 500    , ""  ),

  ("Event"                     , "nGenMuonFromALP" , 50    , 0     , 50    , ""  ),
  ("GenMuonFromALP"            , "pdgId"           , 200   , -100  , 100   , ""  ),
  ("GenMuonFromALP"            , "pt"              , 4000  , 0     , 1000  , ""  ),
  ("GenMuonFromALP"            , "mass"            , 10000 , 0     , 100   , ""  ),
  ("GenMuonFromALP"            , "eta"             , 300   , -3    , 3     , ""  ),
  ("GenMuonFromALP"            , "phi"             , 300   , -3    , 3     , ""  ),
  ("GenMuonFromALP"            , "vx"              , 50000 , -5000 , 5000  , ""  ),
  ("GenMuonFromALP"            , "vy"              , 50000 , -5000 , 5000  , ""  ),
  ("GenMuonFromALP"            , "vz"              , 50000 , -5000 , 5000  , ""  ),
  ("GenMuonFromALP"            , "vxy"             , 50000 , -5000 , 5000  , ""  ),
  ("GenMuonFromALP"            , "boost"           , 2000 , 0      , 1000  , ""  ),
  ("GenMuonFromALP"            , "properVxyALPboost", 50000 , -5000 , 5000  , ""  ),
  ("GenMuonFromALP"            , "dxy"             , 50000 , -5000 , 5000  , ""  ),
  ("Event"                     , "nGenDimuonFromALP" , 50  , 0     , 50    , ""  ),
  ("GenDimuonFromALP"          , "invMass"         , 10000 , 0     , 100   , ""  ),
  ("GenDimuonFromALP"          , "DR"              , 1000  , 0     , 100   , ""  ),
  ("GenDimuonFromALP"          , "Dphi"            , 300   , -3    , 3     , ""  ),
  ("GenDimuonFromALP"          , "pdgId"           , 200   , -100  , 100   , ""  ),
  ("GenDimuonFromALP"          , "pt"              , 4000  , 0     , 1000  , ""  ),
  ("GenDimuonFromALP"          , "mass"            , 10000 , 0     , 100   , ""  ),
  ("GenDimuonFromALP"          , "eta"             , 300   , -3    , 3     , ""  ),
  ("GenDimuonFromALP"          , "phi"             , 300   , -3    , 3     , ""  ),
  ("Event"                     , "nGenALP"         , 50    , 0     , 50    , ""  ),
  ("GenALP"                    , "pdgId"           , 200   , -100  , 100   , ""  ),
  ("GenALP"                    , "pt"              , 4000  , 0     , 1000  , ""  ),
  ("GenALP"                    , "mass"            , 10000 , 0     , 100   , ""  ),
  ("GenALP"                    , "eta"             , 300   , -3    , 3     , ""  ),
  ("GenALP"                    , "phi"             , 300   , -3    , 3     , ""  ),
  ("GenALP"                    , "vx"              , 10000 , -1000 , 1000  , ""  ),
  ("GenALP"                    , "vy"              , 10000 , -1000 , 1000  , ""  ),
  ("GenALP"                    , "vz"              , 10000 , -1000 , 1000  , ""  ),
  ("GenALP"                    , "vxy"             , 10000 , -1000 , 1000  , ""  ),
  ("GenALP"                    , "boost"           , 2000 , 0      , 1000  , ""  ),
  ("GenALP"                    , "dxy"             , 10000 , -1000 , 1000  , ""  ),

  ("Event"          , "nLooseMuonsFromALPSegmentMatch"   , 50    , 0     , 50    , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "pt"               , 2000  , 0     , 1000  , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "eta"              , 300   , -3    , 3     , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "dxy"              , 1600  , -400  , 400   , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "dz"               , 1600  , -400  , 400   , ""  ),
  ("LooseMuonsFromALPSegmentMatch"  , "invMass"          , 10000 , 0     , 100   , ""  ),
  ("Event"          , "nLooseMuonsFromALPSegmentMatch0p1"   , 50    , 0     , 50    , ""  ),
  ("LooseMuonsFromALPSegmentMatch0p1"  , "pt"               , 2000  , 0     , 1000  , ""  ),
  ("LooseMuonsFromALPSegmentMatch0p1"  , "eta"              , 300   , -3    , 3     , ""  ),
  ("LooseMuonsFromALPSegmentMatch0p1"  , "dxy"              , 1600  , -400  , 400   , ""  ),
  ("LooseMuonsFromALPSegmentMatch0p1"  , "dz"               , 1600  , -400  , 400   , ""  ),
  ("LooseMuonsFromALPSegmentMatch0p1"  , "invMass"          , 10000 , 0     , 100   , ""  ),

  ("Event"          , "nLooseMuonsFromALPVertexSegmentMatch"     , 50    , 0     , 50    , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch" , "chi2"           , 500   , 0     , 500   , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch" , "vxy"            , 2000  , -500  , 500   , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch" , "vxySigma"       , 2000  , -500  , 500   , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch" , "vz"             , 2000  , -500  , 500   , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch" , "dR"             , 500   , 0     , 10    , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch" , "idx1"           , 100   , 0     , 100   , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch" , "idx2"           , 100   , 0     , 100   , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch" , "isDSAMuon1"     , 10    , 0     , 10    , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch" , "isDSAMuon2"     , 10    , 0     , 10    , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch" , "displacedTrackIso03Dimuon1"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch" , "displacedTrackIso04Dimuon1"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch" , "displacedTrackIso03Dimuon2"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch" , "displacedTrackIso04Dimuon2"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch" , "displacedTrackIso03Muon1"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch" , "displacedTrackIso04Muon1"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch" , "displacedTrackIso03Muon2"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch" , "displacedTrackIso04Muon2"     , 5000  , 0     , 500    , ""  ),
  ("Event"          , "nLooseMuonsFromALPVertexSegmentMatch0p1"     , 50    , 0     , 50    , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch0p1" , "chi2"           , 500   , 0     , 500   , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch0p1" , "vxy"            , 2000  , -500  , 500   , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch0p1" , "vxySigma"       , 2000  , -500  , 500   , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch0p1" , "vz"             , 2000  , -500  , 500   , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch0p1" , "dR"             , 500   , 0     , 10    , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch0p1" , "idx1"           , 100   , 0     , 100   , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch0p1" , "idx2"           , 100   , 0     , 100   , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch0p1" , "isDSAMuon1"     , 10    , 0     , 10    , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch0p1" , "isDSAMuon2"     , 10    , 0     , 10    , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch0p1" , "displacedTrackIso03Dimuon1"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch0p1" , "displacedTrackIso04Dimuon1"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch0p1" , "displacedTrackIso03Dimuon2"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch0p1" , "displacedTrackIso04Dimuon2"   , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch0p1" , "displacedTrackIso03Muon1"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch0p1" , "displacedTrackIso04Muon1"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch0p1" , "displacedTrackIso03Muon2"     , 5000  , 0     , 500    , ""  ),
  ("LooseMuonsFromALPVertexSegmentMatch0p1" , "displacedTrackIso04Muon2"     , 5000  , 0     , 500    , ""  ),

)

if runLLPNanoAODHistograms:
  histParams = histParams + LLPNanoAOD_histParams

specialBranchSizes = {}